"""Competitor and analog database (Indian + international).

``scale`` cites a source ID where a figure was retrieved. "n/a" means we did
not retrieve a verified figure. Do not fill those cells from memory. Pricing
marked "indicative" comes from public price pages or comparison sites in
2026 and changes often.
"""

# company, country, problem/opp, target customer, product, pricing, scale (with source), model,
# strength, weakness, india_opportunity
COMPETITORS = [
    # ---------------- India: sales / lead generation ----------------
    ("IndiaMART", "India", "P09/O3", "B2B MSME sellers", "B2B lead marketplace + Busy accounting",
     "Annual subscription tiers (silver/gold/etc.)", "FY26 revenue Rs 1,569 cr; 2.28 lakh paying suppliers (S44)",
     "Subscription + lead consumption", "Buyer traffic, brand, cash-rich", "Seller still must convert leads; lead-quality complaints",
     "Partner/integrate: a conversion agent for IndiaMART payers is complementary"),
    ("Justdial", "India", "P09/O3", "Local businesses", "Local search listings + paid campaigns",
     "Annual campaign packages", "FY26 operating revenue Rs 1,213.9 cr; 6.32 lakh paid campaigns; 54.7m listings (S45)",
     "Advertising", "Reach in Tier 2/3", "Consumer-local skew; low B2B depth", "Lead source to integrate"),
    ("TradeIndia / ExportersIndia", "India", "P09/O3", "B2B sellers", "B2B marketplaces", "Membership tiers", "n/a",
     "Subscription", "Long-standing directories", "Smaller traffic than IndiaMART", "Lead source to integrate"),
    ("LeadSquared", "India", "P10/O3", "Mid-market/enterprise sales teams", "CRM + marketing automation", "Per-seat SaaS", "n/a",
     "SaaS", "Deep CRM", "Too complex/expensive for micro and small B2B", "Shows CRM demand; leaves MSME long tail open"),
    ("AiSensy", "India", "P10/O3", "SMBs", "WhatsApp Business API, broadcasts, chatbots", "Rs 1,500-3,500/month (indicative)",
     "2,10,000+ businesses (S49)", "SaaS + message markup", "Low price, self-serve", "Tool not outcome; owner must run it",
     "Validates WhatsApp spend; agent layer on top is the gap"),
    ("Interakt (Jio Haptik)", "India", "P10/O3", "D2C brands, SMBs", "WhatsApp commerce/CRM", "Rs 2,499-3,499/month + ~25% markup (indicative)",
     "n/a", "SaaS + markup", "Jio backing", "D2C focus", "B2B manufacturers underserved"),
    ("Wati", "India/Singapore", "P10/O3", "SMBs", "WhatsApp team inbox + bots", "From ~Rs 2,499/month (indicative)", "n/a",
     "SaaS", "Global reach", "Horizontal", "Same as above"),
    ("Gallabox", "India", "P10/O3", "SMBs", "WhatsApp + no-code bots", "~Rs 2,399/month (indicative)", "10,000+ businesses (S49)",
     "SaaS", "Zoho integration", "Horizontal", "Same as above"),
    # ---------------- India: accounting / compliance ----------------
    ("Tally Solutions", "India", "P04/P05/O2", "MSMEs and their CAs", "Desktop/cloud accounting, GST, inventory",
     "Perpetual + annual renewal (TSS)", "FY25 revenue Rs 500-1,000 cr (range, S47)", "Licence + renewals",
     "De facto standard among CAs; deep GST workflow", "Data entry still manual; limited AI/WhatsApp intake",
     "Build on top of Tally (connector) rather than replace it"),
    ("Busy (IndiaMART)", "India", "P04", "SMB traders", "Accounting/inventory", "Licence", "n/a", "Licence", "IndiaMART distribution",
     "Second to Tally", "Integrate"),
    ("Marg ERP", "India", "P04/P17", "Pharma/FMCG distributors, retailers", "Billing, inventory, accounting", "Licence", "n/a",
     "Licence", "Vertical depth in distribution", "Legacy UX", "Integrate"),
    ("Vyapar", "India", "P04/P17", "Micro/small retailers and traders", "Mobile/desktop billing, GST", "Annual plans (low ticket)",
     "1m+ businesses (vendor claim)", "Freemium SaaS", "Simple vernacular UX", "Low ARPU, churn", "Do not compete head-on"),
    ("myBillBook (FloBiz)", "India", "P04/P17", "Micro/small traders", "Billing, inventory, payments", "Annual plans (low ticket)",
     "1m+ MAU (vendor claim)", "Freemium SaaS + fintech", "Mobile-first", "Low ARPU", "Do not compete head-on"),
    ("Zoho (Books, CRM, Payroll)", "India", "P04/P07/P10", "SMBs to enterprises", "Full SaaS suite", "Per-org SaaS",
     "Group FY25 revenue Rs 12,313 cr (global) (S47)", "SaaS", "Breadth, price, India presence", "Generic; needs digital maturity",
     "Partner for L3+ customers"),
    ("Clear (ClearTax)", "India", "P04/P05/P06", "Enterprises, CAs, SMBs", "GST, e-invoicing, ITR, AP automation", "SaaS",
     "FY25 revenue Rs 272 cr; loss Rs 96 cr (S47)", "SaaS", "Compliance depth, enterprise logos", "Lower focus on micro-CA workflow",
     "Competes with O2; differentiate on WhatsApp intake + Tally posting for small CA firms"),
    ("Suvit", "India", "P05/O2", "CA firms", "Automation of data entry into Tally (bank statements, invoices)", "Per-firm SaaS",
     "n/a", "SaaS", "CA focus", "Scale unknown", "Closest analog to O2; validate WTP and gaps"),
    ("Khatabook", "India", "P04/P25", "Micro merchants", "Digital ledger, billing, payments", "Free + paid add-ons",
     "FY24 revenue Rs 102.7 cr (S47)", "Freemium + fintech", "Huge user base", "Monetisation difficult", "Avoid segment"),
    ("OkCredit", "India", "P04", "Micro merchants", "Digital ledger", "Free + paid", "FY25 revenue Rs 23.3 cr; loss Rs 23.2 cr (S47)",
     "Freemium", "Simplicity", "Weak monetisation", "Evidence of low WTP at micro end"),
    ("Vakilsearch / IndiaFilings", "India", "P07/P08/P32", "Startups and small firms", "Registrations, filings, compliance services",
     "Per-service fees", "IndiaFilings FY25 revenue Rs 88.5 cr (S47)", "Services marketplace", "Distribution via search",
     "Transactional, low retention", "Shows paid demand for compliance services"),
    ("TeamLease RegTech", "India", "P07/P08", "Enterprises, large factories", "Compliance management software + content",
     "Enterprise contracts", "n/a", "SaaS", "Legal content depth", "Enterprise pricing", "MSME version is a gap (O12 adjacent)"),
    ("greytHR / Keka / Zimyo", "India", "P07/O12", "SMB-midmarket HR", "Payroll/HR SaaS", "Per-employee SaaS", "n/a", "SaaS",
     "Mature payroll", "Need HR admin; compliance filings often outsourced", "Managed service layer for 10-200 staff firms"),
    ("PagarBook", "India", "P25", "Micro employers", "Attendance and wage app", "Freemium", "n/a", "Freemium", "Simple",
     "Low WTP", "Avoid"),
    # ---------------- India: receivables / credit ----------------
    ("RXIL (TReDS)", "India", "P01/O1", "MSME sellers + corporate buyers", "Invoice discounting exchange", "Transaction fees",
     "1,03,998 MSME sellers; 3,759 buyers (Jul-2026) (S23)", "Exchange fees", "Regulated, SIDBI/NSE-backed",
     "Requires buyer onboarding; only buyer-accepted invoices", "Integrate as finance rail; CPSE mandate expands (S24)"),
    ("Invoicemart (A.TReDS)", "India", "P01/O1", "MSME sellers", "TReDS", "Transaction fees", "68,663 sellers; 4,496 buyers (Jul-2026) (S23)",
     "Exchange fees", "Axis-backed", "Buyer-side constraint", "Integrate"),
    ("M1xchange / C2treds / DTX (KredX)", "India", "P01/O1", "MSME sellers", "TReDS", "Transaction fees",
     "C2FO cites ~2 lakh suppliers on its India network (S57)", "Exchange fees", "Competition among 5 TReDS", "Same buyer limit",
     "Integrate multiple rails"),
    ("Recordent", "India", "P01/O1", "SMEs", "Credit reporting of defaulters, collections", "Subscription/fees",
     "Analysed ~1.1 lakh MSMEs for 2026 report (S22)", "SaaS + services", "Bureau reporting deterrent", "Narrow workflow",
     "Partner for escalation, or competitor"),
    ("Vayana", "India", "P01/P02", "Anchors + their supply chains", "Supply-chain finance platform", "Fees", "n/a",
     "Fee + finance", "Anchor programmes", "Anchor-led only", "Embedded finance partner"),
    ("FlexiLoans", "India", "P02/O15", "MSMEs", "Digital unsecured business loans", "Interest", "AUM > Rs 3,000 cr; 70k+ MSMEs (S48)",
     "NBFC lending", "Digital, profitable", "Credit risk, competition", "Lender partner for O1/O15"),
    ("Lendingkart", "India", "P02/O15", "MSMEs", "Digital business loans", "Interest", "Cumulative Rs 18,700 cr disbursed (S48)",
     "NBFC lending", "Scale", "Cyclical funding", "Lender partner"),
    ("Indifi", "India", "P02/O15", "MSMEs", "Business loans, invoice discounting", "Interest", "n/a", "Lending marketplace + NBFC",
     "Partnerships", "Competition", "Lender partner"),
    ("Banks (SBI, HDFC, ICICI, Axis, PSBs)", "India", "P02/P29", "All MSMEs", "Loans, TReDS, trade finance, digital credit model",
     "Interest", "PSB digital model Rs 52,300 cr sanctioned Apr-Dec 2025 (S27)", "Lending", "Cheapest capital", "Process-heavy",
     "Channel partners and lenders"),
    # ---------------- India: procurement / supply chain ----------------
    ("OfBusiness (+Oxyzo)", "India", "P14/P15/O4", "SME manufacturers, contractors", "Raw-material procurement + credit",
     "Margin on goods + interest", "FY25 revenue Rs 22,241 cr, PAT Rs 597 cr; Oxyzo revenue Rs 1,207 cr (S46)",
     "Commerce + lending", "Proven model, profitable", "Horizontal; less cluster depth in some categories",
     "Proof of WTP; a vertical entrant must pick categories they under-serve"),
    ("Zetwerk", "India", "P15", "OEMs (buy side)", "Contract manufacturing network", "Margin", "FY25 revenue Rs 12,798 cr (S46)",
     "Manufacturing marketplace", "Large OEM demand", "Buy-side focus", "MSMEs as supply partners"),
    ("Infra.Market", "India", "P15", "Construction contractors, builders", "Construction materials + private labels", "Margin",
     "FY25 gross revenue Rs 18,472 cr (S46)", "Commerce", "Private labels", "Construction-focused", "Category reference"),
    ("Moglix", "India", "P15", "Industrial MRO buyers", "MRO procurement", "Margin", "FY24 revenue Rs 4,964 cr (S46)", "Commerce",
     "Enterprise MRO", "Enterprise skew", "Category reference"),
    ("Udaan", "India", "P15", "Retailers/kiranas", "B2B e-commerce", "Margin", "n/a", "Commerce", "Retail reach", "Losses historically",
     "Avoid kirana B2B"),
    ("Bizongo", "India", "P15", "Brands needing packaging", "Packaging procurement + finance", "Margin", "n/a", "Commerce + finance",
     "Category depth", "Narrow", "Category reference"),
    ("Shiprocket / Delhivery / Porter", "India", "P16", "SMB shippers", "Logistics aggregation", "Per shipment", "n/a", "Aggregation",
     "Network", "Parcel/D2C focus vs cluster FTL/PTL", "Cluster freight pooling is a gap"),
    # ---------------- India: manufacturing / energy / ESG ----------------
    ("Infinite Uptime", "India", "P20/O10", "Large process plants", "Predictive maintenance", "Enterprise", "$35m Series C (S71)",
     "Hardware + SaaS", "AI depth", "Enterprise pricing", "MSME-grade version is a gap"),
    ("Altizon", "India", "P19/P20/O10", "Enterprises", "IIoT platform (Datonis)", "Subscription by devices/data", "270+ IIoT projects, 130+ enterprises (S71)",
     "SaaS + services", "Platform", "Enterprise", "Gap at MSME end"),
    ("Faclon Labs", "India", "P20/P22", "Industrial clients", "IoT + energy monitoring", "Project/SaaS", "n/a", "SaaS + hardware",
     "Energy/ESG angle", "Scale unknown", "Partner for O5/O10"),
    ("C&I solar developers (Fourth Partner, Cleantech Solar, Amplus, others)", "India", "P22/O5", "Large C&I consumers",
     "Rooftop/open-access solar, PPA/RESCO", "PPA tariff", "n/a", "Project finance", "Capital access", "Avoid small, credit-risky MSMEs",
     "MSME cluster RESCO with pooled credit enhancement is a gap"),
    ("Sprih / Breathe ESG / others", "India", "P30/P31/O6", "Listed companies, exporters", "ESG, BRSR and CBAM software",
     "SaaS", "n/a", "SaaS", "Regulatory content", "Sell to large firms, not MSME suppliers", "MSME supplier-side data + verification is a gap"),
    # ---------------- India: exports / schemes / tenders ----------------
    ("Skydo", "India", "P28", "Exporters, freelancers", "Cross-border collections", "Flat fee", "40,000+ exporters (May-2026); ~$19.7m raised (S50)",
     "Payments", "Price transparency", "Crowded", "Avoid; partner"),
    ("BriskPe / Xflow / Infinity / Wise / Payoneer", "India/Global", "P28", "Exporters", "Cross-border payments", "Fees/FX",
     "BriskPe $5m seed (S50)", "Payments", "Various", "Crowded", "Avoid"),
    ("Drip Capital", "US/India", "P29", "Small exporters", "Collateral-free trade finance", "Interest/fees",
     "MoU to disburse Rs 10,000 cr to Maharashtra MSME exporters 2026-31 (S50)", "Lending", "Export focus", "Credit cycles",
     "Finance partner for O9"),
    ("Alibaba.com / Amazon Global Selling", "Global", "P26/O9", "Exporters", "Cross-border marketplaces", "Membership/fees", "n/a",
     "Marketplace", "Buyer reach", "Sellers need listings, compliance, fulfilment", "Managed onboarding is a service gap"),
    ("Volza / Eximpedia (trade data)", "India", "P26/O9", "Exporters", "Shipment-level trade data", "Subscription", "n/a", "Data SaaS",
     "Data depth", "Data, not outcomes", "Data input for O9"),
    ("Haqdarshak", "India", "P32/O7", "Citizens, micro enterprises", "Scheme discovery + assisted access (6,000+ schemes)",
     "B2B2C partnerships (banks/CSR)", "n/a (S61)", "Partnerships", "Field network", "Micro/welfare focus", "High-value incentives for growing MSMEs open"),
    ("Tender discovery portals (TenderTiger, BidAssist, Tender247)", "India", "P34/O8", "Bidders", "Tender alerts + documents",
     "Subscription", "n/a", "SaaS", "Coverage", "Alerts, not bid preparation", "AI bid desk gap"),
    ("Government platforms (GeM, ONDC, Udyam, TReDS, Samadhaan, MyScheme)", "India", "Multiple", "All MSMEs", "Public digital infrastructure",
     "Free", "GeM FY26 Rs 5 lakh cr (S34)", "Public", "Free, mandated", "Usability, discovery", "Build on DPI; do not compete"),
    ("Apna / WorkIndia", "India", "P23", "Employers of blue/grey-collar workers", "Job marketplace", "Job-post fees", "n/a",
     "Marketplace", "Candidate scale", "Generic; skilled trades thin", "Cluster ITI pipeline gap (O16)"),
    # ---------------- International analogs ----------------
    ("Pennylane", "France", "O2", "SMEs and their accountants", "Accounting platform shared by firm + accountant", "SaaS",
     "EUR 115m ARR (2025); funding talks at ~$4.25bn valuation (S57)", "SaaS via accountants", "Accountant-led distribution",
     "France-specific", "Proves accountant-channel model (O2)"),
    ("Dext / Hubdoc", "UK/Canada", "O2", "Accountants and bookkeepers", "Document capture and auto-posting", "SaaS", "n/a", "SaaS",
     "Accountant channel", "Not India/GST-native", "Analog for WhatsApp-to-Tally intake"),
    ("Botkeeper", "US", "O2", "Accounting firms", "AI + human bookkeeping", "Per client", "n/a", "SaaS + service", "Hybrid model",
     "US-only", "Analog for assisted AI bookkeeping"),
    ("Agicap", "France", "P03", "SMEs", "Cash-flow forecasting", "SaaS", "$100m raised (2021) (S57)", "SaaS", "European scale",
     "Needs bank-data maturity", "Feature inside O1"),
    ("Chaser / Upflow / Tesorio / Versapay", "UK/France/US", "O1", "SMB-midmarket finance teams", "Accounts-receivable automation",
     "SaaS", "n/a", "SaaS", "Proven AR automation", "No WhatsApp/vernacular, no MSMED legal rails", "Proven elsewhere -> adapt for India (O1)"),
    ("Bill.com", "US", "O1", "SMBs", "AP/AR automation + payments", "SaaS + payments", "n/a (public company)", "SaaS + payments",
     "Network effects", "US-centric", "Analog"),
    ("C2FO", "US", "O1", "Suppliers of large buyers", "Early-payment marketplace", "Discount fees",
     "$350bn+ cumulative funding; ~2 lakh suppliers in India network (S57)", "Marketplace", "Buyer network", "Buyer-led",
     "Already in India (C2treds)"),
    ("Moniepoint", "Nigeria", "O15", "Micro and small businesses", "Payments + banking + credit", "Fees + interest",
     "$200m+ Series C (2025); $700m MSME loans in 2025 (S57)", "Fintech", "Agent network", "Market-specific", "Distribution-led fintech analog"),
    ("Konfio", "Mexico", "O15", "SMEs", "Credit + SaaS", "Interest", "$227m credit line (S57)", "Lending", "Data underwriting", "Market-specific", "Analog"),
    ("BukuWarung", "Indonesia", "P04", "Micro merchants", "Bookkeeping + payments", "Freemium", "$80m raised; 6.5m users (S57)", "Fintech",
     "Scale", "Low ARPU", "Same lesson as Khatabook: avoid micro SaaS"),
    ("Mekari", "Indonesia", "O12/P04", "SMEs", "HR, payroll, accounting, CRM suite", "SaaS", "$50m round (S57)", "SaaS",
     "Suite breadth", "Indonesia", "Analog for SME suite"),
    ("KiotViet", "Vietnam", "P17", "Retail MSMEs", "POS + inventory", "SaaS", "$45m Series B; 150k MSMEs (S57)", "SaaS", "POS depth", "Retail", "Analog"),
    ("Katana", "Estonia", "O10", "SMB manufacturers", "Cloud manufacturing ERP/inventory", "SaaS",
     "EUR 14m Series B extension (Oct 2025); 1,500+ SMBs (S57)", "SaaS", "Simple MRP", "Western SMBs", "Analog for O10"),
    ("Guidewheel", "US", "O10", "Mid-sized factories", "Clip-on sensors + FactoryOps", "Per-sensor SaaS", "$9m Series A (2022) (S57)",
     "SaaS + hardware", "Universal clip-on sensor", "US-centric", "Proven elsewhere -> adapt (O10)"),
    ("MachineMetrics", "US", "O10", "Discrete manufacturers", "Machine monitoring/analytics", "SaaS", "$20m Series B (2021) (S57)",
     "SaaS", "CNC connectivity", "Higher price point", "Analog"),
    ("Kommo / Yalo", "US/LatAm", "O3", "SMBs / CPG distributors", "WhatsApp CRM / conversational commerce", "SaaS", "n/a", "SaaS",
     "WhatsApp-first in LatAm", "Not India B2B", "Proves WhatsApp-first sales tooling"),
    ("Alibaba.com / 1688", "China", "P26/P15", "Global B2B buyers/sellers", "B2B sourcing marketplace", "Memberships", "n/a",
     "Marketplace", "Liquidity", "China-centric", "Export channel for Indian MSMEs"),
    ("Kingdee / Yonyou", "China", "P04", "SMEs", "Cloud ERP/accounting", "SaaS", "n/a", "SaaS", "Scale in China", "Not in India", "Analog"),
    ("Faire / Tradeling", "US / UAE", "P26/O9", "Independent retailers / MENA B2B", "Wholesale marketplaces", "Commission", "n/a",
     "Marketplace", "Curated demand", "Selective", "Export channel"),
    ("Wafeq", "Saudi Arabia", "P04", "SMEs", "E-invoicing-compliant accounting (ZATCA)", "SaaS", "n/a", "SaaS",
     "Regulation-led adoption", "Market-specific", "Analog: regulation-led SaaS adoption"),
    ("Sweep / Greenly / Normative", "France/Sweden", "O6", "Mid-market and enterprises", "Carbon accounting", "SaaS", "n/a", "SaaS",
     "EU regulatory fit", "Expensive for MSMEs; not CBAM-supplier-native", "Supplier-side CBAM for Indian MSMEs is a gap"),
    ("Gusto", "US", "O12", "SMBs", "Payroll + HR + compliance", "Per employee", "n/a", "SaaS", "Compliance automation", "US-only",
     "Analog for managed payroll"),
]
