"""Startup opportunity shortlist, TAM/SAM/SOM inputs, opportunity matrix and unit economics.

All TAM/SAM/SOM are ANNUAL REVENUE to the startup (not customer spend or GMV)
in Rs crore unless noted. Bottom-up = customers x ARPU. Top-down = a spend or
value pool x a capturable share. Every input is an assumption to validate.
The basis for customer counts is in ``customers_basis``.
"""

CR = 1e7  # rupees per crore

OPPORTUNITIES = [
    dict(
        id="O1", name="AI receivables & collections copilot (AR-OS) for B2B MSMEs",
        problems="P01;P41;P03;P02",
        target="B2B manufacturers, distributors and B2B service firms with Rs 2-250 cr turnover (owner + accountant)",
        tam_customers=900_000, arpu=60_000,
        customers_basis="~7 lakh firms >= Rs 5 cr (e-invoice anchor) + ~half of 15-22 lakh firms at Rs 1.5-5 cr that sell B2B; "
                        "haircut to 9 lakh B2B-heavy",
        topdown_low_cr=3_670, topdown_high_cr=8_100,
        topdown_method="0.5-1.0% annual revenue capture on Rs 7.34-8.1 lakh cr overdue MSME receivables (S20, S19)",
        sam_customers=300_000, sam_arpu=60_000,
        sam_basis="e-invoicing manufacturers and wholesalers in top-100 MSME districts",
        som_customers=(6_000, 12_000), som_arpu=60_000,
        pain="Very high", alternatives="Owner phone calls, lawyers, MSEFC/Samadhaan, TReDS, Recordent",
        why_insufficient="TReDS needs buyer onboarding and accepted invoices (~8k buyers); MSEFC is slow; nobody automates "
                         "daily follow-up, promise-to-pay tracking, statutory-interest computation and escalation in vernacular on WhatsApp",
        solution="Ingest invoices (Tally/e-invoice/GSTR-1), score debtors, run AI WhatsApp/voice reminders in buyer's language, compute "
                 "MSMED s.16 interest and 43B(h) exposure, generate legal notices, one-click ODR/MSEFC filing, route eligible invoices to "
                 "TReDS/NBFC for early payment",
        model="SaaS (Rs 2-6k/month) + success fee on recovered overdue (1-3%) + financing referral fees",
        pricing="Rs 2,000-6,000/month; success fee 1-3% on recovered > 90-day dues",
        competition="Low-Medium", acquisition="CA firms (bundle with O2), industry associations, TReDS platforms, Tally partners; "
                                              "WhatsApp-first demo showing 'money recovered in 30 days'",
        mvp_complexity="Medium", time_to_mvp="8-12 weeks", capital="Rs 2-4 cr to PMF; Rs 25-60 cr to scale",
        gross_margin="70-80%", regulatory_risk="Low-Medium (RBI digital-lending rules for referrals; fair-collection conduct)",
        tech_risk="Low", expansion="Payables, cash-flow forecasting, credit underwriting, buyer credit-risk data",
        international="Yes: SE Asia, MENA, Africa SME AR markets (WhatsApp-heavy)",
        evidence="Strong on problem (official + 1.1 lakh-firm dataset); WTP for software unproven, for recovery proven (lawyers, agents)",
        category="A",
        matrix=dict(market="High", severity="High", wtp="Medium", competition="Low-Medium", cac="Medium", mvp="Medium",
                    scalability="High", potential="High", confidence="High"),
    ),
    dict(
        id="O2", name="AI copilot for CA firms (WhatsApp intake -> Tally posting -> GST/TDS reconciliation)",
        problems="P05;P04;P06;P42",
        target="CA and tax-practitioner firms (2-50 staff) serving MSME clients",
        tam_customers=100_000, arpu=120_000,
        customers_basis="98,967 ICAI-registered firms + 1.6 lakh COP holders (overlap) + non-CA tax practitioners (count unavailable)",
        topdown_low_cr=1_000, topdown_high_cr=1_500,
        topdown_method="1.49 cr normal GST filers x ~70% served by professionals x Rs 100-150/client-month of automation value",
        sam_customers=40_000, sam_arpu=120_000, sam_basis="Firms with >= 3 staff in top-100 cities",
        som_customers=(3_000, 5_000), som_arpu=150_000,
        pain="High (staff shortage, due-date crunch)",
        alternatives="Articled staff, Tally, GST utilities, Clear, Suvit, practice-management tools",
        why_insufficient="Data still arrives as WhatsApp photos, PDFs and bank statements; posting into Tally and 2B/IMS reconciliation remain manual",
        solution="WhatsApp document intake per client, OCR + LLM classification, auto-voucher creation in Tally, bank/UPI reconciliation, "
                 "GSTR-2B/IMS matching, vendor nudges, notice drafting; human-in-the-loop review",
        model="Per-firm SaaS by client count", pricing="Rs 3,000-50,000/month by client count",
        competition="Medium", acquisition="ICAI branch CPE seminars, CA WhatsApp/Telegram communities, Tally partner network, referrals",
        mvp_complexity="Medium", time_to_mvp="8-10 weeks", capital="Rs 1.5-3 cr to PMF; Rs 15-40 cr to scale",
        gross_margin="75-85%", regulatory_risk="Low (DPDP compliance)", tech_risk="Low-Medium (OCR on poor images)",
        expansion="Each CA firm is a channel to 50-500 MSMEs for O1, O15, O12",
        international="Yes: accountant-led markets (SE Asia, Middle East with VAT/e-invoicing)",
        evidence="Medium-strong: CAs pay for software today; Pennylane proves accountant-channel model",
        category="A",
        matrix=dict(market="Medium", severity="Medium-High", wtp="High", competition="Medium", cac="Low", mvp="Medium",
                    scalability="High", potential="Medium-High", confidence="Medium"),
    ),
    dict(
        id="O3", name="AI B2B sales agent on WhatsApp/voice (lead response, qualification, quotes, follow-up)",
        problems="P10;P09;P13;P11",
        target="B2B MSMEs that already pay for leads (IndiaMART, Justdial, TradeIndia, Google Ads)",
        tam_customers=1_000_000, arpu=48_000,
        customers_basis="4-6 lakh MSMEs paying for leads (2.28 lakh IndiaMART payers; 6.3 lakh Justdial campaigns, partly B2C) + broader B2B sellers",
        topdown_low_cr=1_050, topdown_high_cr=2_500,
        topdown_method="30-50% of a Rs 3,500-5,000 cr MSME lead-spend pool (IndiaMART Rs 1,569 cr + Justdial Rs 1,214 cr + others)",
        sam_customers=400_000, sam_arpu=48_000, sam_basis="Active B2B lead buyers",
        som_customers=(10_000, 20_000), som_arpu=48_000,
        pain="High", alternatives="Owner/salesperson phone, WhatsApp Business app, IndiaMART lead manager, WhatsApp BSP tools",
        why_insufficient="Leads go cold within hours; tools need someone to run them; no vernacular, product-aware agent that quotes and follows up",
        solution="Unified inbox for all lead sources; AI agent replies within 60 seconds in buyer's language, qualifies, sends catalogue/quote, "
                 "books calls, follows up; owner approves quotes on WhatsApp",
        model="SaaS + usage (conversations)", pricing="Rs 2,500-8,000/month",
        competition="Medium", acquisition="Outbound to publicly listed lead-buyers by category/cluster; IndiaMART-integrated onboarding; "
                                           "ROI guarantee (reply time, conversion uplift)",
        mvp_complexity="Medium", time_to_mvp="6-10 weeks", capital="Rs 2-4 cr to PMF; Rs 30-80 cr to scale",
        gross_margin="55-70% (LLM + WhatsApp conversation costs)", regulatory_risk="Low-Medium (WhatsApp policy, DPDP consent)",
        tech_risk="Medium (accuracy of quotes, hallucination control)",
        expansion="CRM, catalogue/storefront (O14), distributor ordering, export inquiries (O9)",
        international="Yes: WhatsApp-first SMB markets (LatAm, Indonesia, MENA, Africa)",
        evidence="Strong on spend (Rs 2,700+ cr lead spend); conversion pain inferred; agent WTP to validate",
        category="A",
        matrix=dict(market="High", severity="High", wtp="High", competition="Medium", cac="Medium", mvp="Medium",
                    scalability="High", potential="High", confidence="Medium"),
    ),
    dict(
        id="O4", name="Vertical, cluster-focused procurement + embedded credit (one input category)",
        problems="P15;P14;P02;P16",
        target="Manufacturers in 3-5 clusters buying one category (e.g., yarn/fabric in Surat-Bhiwandi-Tiruppur or polymers in plastics clusters)",
        tam_customers=None, arpu=None,
        customers_basis="Top-down only; GMV business",
        topdown_low_cr=62_000, topdown_high_cr=124_000,
        topdown_method="Take-rate revenue: Rs 124.9 lakh cr MSME procurement (S31) x 25% in metals/polymers/yarn/chemicals x 2-4% take",
        sam_customers=50_000, sam_arpu=60 * 100_000 * 0.04,
        sam_basis="50,000 buyers in 5 clusters x Rs 60 lakh/yr category purchases (assumption) x 4% take",
        som_customers=(2_000, 4_000), som_arpu=60 * 100_000 * 0.04,
        pain="High", alternatives="Local traders on credit, OfBusiness, Udaan, Moglix, Bizongo",
        why_insufficient="Horizontal players optimise for large tickets; small buyers need cluster delivery, credit and price-lock at their scale",
        solution="Cluster desk with price intelligence, pooled buying, assured quality, 30-60 day credit via NBFC partner, freight pooling",
        model="Trading margin + credit spread/referral", pricing="2-5% gross margin on GMV + credit income",
        competition="High", acquisition="Field sales in cluster, association tie-ups, trader-turned-agents",
        mvp_complexity="High (ops + working capital)", time_to_mvp="3-4 months", capital="Rs 10-25 cr pilot incl. working capital; Rs 300 cr+ to scale",
        gross_margin="2-5% of GMV (20-40% of net revenue after logistics)", regulatory_risk="Medium (lending via NBFC partner)",
        tech_risk="Low", expansion="More categories, sell-side (O3), export sourcing",
        international="Limited (cluster-specific); possible in SE Asia",
        evidence="Very strong spend evidence (OfBusiness Rs 22,241 cr FY25 revenue); hard for new entrants",
        category="A (hard)",
        matrix=dict(market="Very high", severity="High", wtp="High", competition="High", cac="Medium", mvp="High",
                    scalability="Medium", potential="High", confidence="High"),
    ),
    dict(
        id="O5", name="Energy-as-a-service for MSME clusters (rooftop solar RESCO + monitoring + retrofits)",
        problems="P22",
        target="Energy-intensive MSME units (foundry, forging, ceramics, dyeing, plastics, cold storage) with 50-1,000 kW load",
        tam_customers=130_000, arpu=0.15 * 75 * 100_000,
        customers_basis="Est. 1.1-1.6 lakh energy-relevant units (40-60% of 2.67 lakh ASI factories); 150 kW average solar potential (assumption)",
        topdown_low_cr=10_000, topdown_high_cr=19_000,
        topdown_method="BEE-era estimate of Rs 19,000 cr/yr MSME savings potential, plus solar PPA revenue at ~Rs 75 lakh/MW-yr",
        sam_customers=15_000, sam_arpu=0.10 * 75 * 100_000, sam_basis="5 target clusters x 0.1 MW average",
        som_customers=(1_500, 3_000), som_arpu=0.10 * 75 * 100_000,
        pain="High", alternatives="Grid power, diesel, self-funded rooftop via local EPC, large C&I developers",
        why_insufficient="Developers avoid small, unrated MSMEs; MSMEs lack capex and trust; efficiency audits rarely implemented",
        solution="Zero-capex rooftop solar + energy monitoring + financed retrofits; pooled credit enhancement per cluster",
        model="PPA/lease (10-25 yrs) + monitoring SaaS + shared-savings", pricing="Tariff 10-25% below grid; savings share",
        competition="Medium", acquisition="Cluster associations, discom data, demo installations, bank partners",
        mvp_complexity="High (capex)", time_to_mvp="3-6 months", capital="Rs 5-10 cr equity + project debt; Rs 500 cr+ at scale",
        gross_margin="Infra-like (project IRR 14-18% target)", regulatory_risk="Medium (state net-metering rules)",
        tech_risk="Low", expansion="Carbon credits, CBAM data (O6), storage, EV logistics",
        international="Limited",
        evidence="Medium: savings well documented; MSME credit risk is the binding constraint",
        category="B",
        matrix=dict(market="High", severity="High", wtp="Medium-High", competition="Medium", cac="Medium", mvp="High",
                    scalability="Medium", potential="High", confidence="Medium"),
    ),
    dict(
        id="O6", name="CBAM & product-carbon-footprint compliance for MSME exporters and suppliers",
        problems="P30;P31;P22",
        target="Steel/aluminium (and later other) exporters to EU, their upstream suppliers, and suppliers to BRSR-reporting firms",
        tam_customers=None, arpu=None,
        customers_basis="3-4k direct + 25-30k indirect CBAM-exposed MSMEs (S38) + est. 20-50k BRSR value-chain suppliers",
        topdown_low_cr=450, topdown_high_cr=750,
        topdown_method="Segment sum: 3,500 x Rs 6 lakh + 27,500 x Rs 0.9 lakh + 35,000 x Rs 37,500 = ~Rs 590 cr",
        sam_customers=None, sam_arpu=None, sam_fraction=0.6, sam_basis="60% of TAM in steel/aluminium/engineering clusters",
        som_customers=(800, 1_500), som_arpu=192_000,
        pain="Very high (orders lost)", alternatives="Consultants, EU buyer templates, global carbon software",
        why_insufficient="Global tools target large importers; MSMEs lack metering and data; default values penalise them 30-80%",
        solution="Plant-level data capture (bills, meters, production), CBAM-methodology emissions per product, supplier data requests, "
                 "verifier-ready reports, abatement roadmap (links O5)",
        model="Annual subscription + verification coordination fee", pricing="Direct exporters Rs 4-8 lakh/yr; suppliers Rs 0.6-1.2 lakh/yr",
        competition="Low-Medium", acquisition="EEPC/AIIFA/cluster workshops, EU importer referrals, banks financing exporters",
        mvp_complexity="Medium", time_to_mvp="8-12 weeks", capital="Rs 1-2.5 cr to PMF; Rs 10-25 cr to scale",
        gross_margin="60-75%", regulatory_risk="Medium (methodology changes; verifier accreditation)",
        tech_risk="Low", expansion="UK CBAM, EU battery/ecodesign passports, carbon credits, green finance",
        international="Yes: exporters in Turkey, Vietnam, Egypt, Ukraine etc. face the same CBAM rules",
        evidence="Strong on pain (regulation in force; documented order losses); market small but urgent",
        category="A (niche)",
        matrix=dict(market="Low-Medium", severity="Very high", wtp="Medium-High", competition="Low", cac="Low", mvp="Medium",
                    scalability="Medium-High", potential="Medium", confidence="Medium"),
    ),
    dict(
        id="O7", name="Incentive & scheme claims-as-a-service (success fee)",
        problems="P33;P32;P40",
        target="MSMEs investing in plant/expansion (capital subsidy, interest subvention, SGST reimbursement, ZED, CGTMSE)",
        tam_customers=150_000, arpu=30_000,
        customers_basis="Assumed 1.5 lakh claims/yr; avg benefit Rs 6 lakh x 5% fee = Rs 30k (low confidence)",
        topdown_low_cr=300, topdown_high_cr=600, topdown_method="Unclaimed/claimable benefit pool x 5% success fee (pool unmeasured)",
        sam_customers=25_000, sam_arpu=50_000, sam_basis="High-value claims in 3 states (Gujarat, Maharashtra, Tamil Nadu)",
        som_customers=(2_000, 5_000), som_arpu=50_000,
        pain="Medium-High", alternatives="Local consultants, bank staff, Haqdarshak, government portals",
        why_insufficient="Fragmented consultants, opaque eligibility, long disbursal cycles",
        solution="Eligibility engine across central + state schemes; document automation; claim tracking; success-fee consultants on a platform",
        model="Success fee 3-8% + filing fees", pricing="3-8% of benefit received",
        competition="Medium", acquisition="CA firms, banks, associations; scheme engine as free lead magnet",
        mvp_complexity="Low-Medium", time_to_mvp="6-8 weeks", capital="Rs 0.5-1.5 cr", gross_margin="50-65%",
        regulatory_risk="Low", tech_risk="Low", expansion="Lending (O15), insurance (O13)", international="Low",
        evidence="Weak-medium: consultant practice exists; size and collection risk unmeasured", category="B",
        matrix=dict(market="Medium", severity="Medium", wtp="Medium", competition="Medium", cac="Medium", mvp="Low",
                    scalability="Medium", potential="Low-Medium", confidence="Low"),
    ),
    dict(
        id="O8", name="AI bid desk for GeM and public tenders",
        problems="P34",
        target="MSE sellers on GeM and state tender portals",
        tam_customers=250_000, arpu=30_000,
        customers_basis="11 lakh+ MSEs registered on GeM (S34); assume 2-3 lakh active bidders",
        topdown_low_cr=600, topdown_high_cr=800,
        topdown_method="0.25-0.35% of Rs 2.36 lakh cr MSME GeM order value (FY26)",
        sam_customers=60_000, sam_arpu=36_000, sam_basis="Bidders with prior awards",
        som_customers=(5_000, 8_000), som_arpu=36_000,
        pain="Medium", alternatives="Tender alert portals, consultants", why_insufficient="Alerts, not eligibility checks, document prep, pricing intelligence",
        solution="Tender matching, eligibility/compliance checklist, AI document preparation, L1 price intelligence, post-award tracking",
        model="Subscription + optional success fee", pricing="Rs 2,000-5,000/month; 0.5% of awarded value optional",
        competition="Medium-High", acquisition="GeM seller communities, MSME-DFO workshops, CA firms",
        mvp_complexity="Medium", time_to_mvp="8-10 weeks", capital="Rs 1-2 cr", gross_margin="70-80%",
        regulatory_risk="Low", tech_risk="Low", expansion="Private enterprise RFQs, export tenders", international="Medium",
        evidence="Medium", category="B",
        matrix=dict(market="Medium", severity="Medium", wtp="Medium", competition="Medium-High", cac="Medium", mvp="Medium",
                    scalability="High", potential="Medium", confidence="Medium"),
    ),
    dict(
        id="O9", name="Export launchpad for export-capable non-exporters (managed service + buyer data + finance)",
        problems="P26;P27;P29",
        target="Small and medium manufacturers with export-grade products but no/limited exports",
        tam_customers=300_000, arpu=200_000,
        customers_basis="1.73 lakh exporting MSMEs (FY25) + est. 1-2 lakh export-capable non-exporters (low confidence)",
        topdown_low_cr=1_500, topdown_high_cr=3_000,
        topdown_method="Share of EPM Niryat Disha-supported spend + marketplace/fair spend (unmeasured)",
        sam_customers=15_000, sam_arpu=200_000, sam_basis="3 product categories x 10 clusters",
        som_customers=(600, 1_200), som_arpu=200_000,
        pain="Medium-High", alternatives="EPCs, trade fairs, Alibaba.com, agents, freight forwarders",
        why_insufficient="Long, risky first-export journey; no single accountable partner", solution="Readiness audit, compliance/certification, "
        "listing + buyer outreach, sample logistics, finance and payments partners", model="Retainer + success commission",
        pricing="Rs 1-3 lakh/yr + 2-5% of first-year exports", competition="Medium", acquisition="EPCs, district export hubs, cluster associations",
        mvp_complexity="Medium (service-heavy)", time_to_mvp="3 months", capital="Rs 2-5 cr", gross_margin="40-55%",
        regulatory_risk="Low", tech_risk="Low", expansion="Trade finance, logistics", international="Inbound buyers globally",
        evidence="Medium-low", category="B",
        matrix=dict(market="Medium", severity="Medium-High", wtp="Medium", competition="Medium", cac="Medium-High", mvp="Medium",
                    scalability="Low-Medium", potential="Medium", confidence="Low"),
    ),
    dict(
        id="O10", name="WhatsApp-native shop-floor digitisation for job shops (production tracking + clip-on machine sensors)",
        problems="P19;P20;P21",
        target="Engineering/plastics job shops with 5-100 machines in auto/engineering clusters",
        tam_customers=150_000, arpu=60_000,
        customers_basis="Subset of 2.67 lakh ASI factories + unregistered job shops (low confidence)",
        topdown_low_cr=600, topdown_high_cr=1_200, topdown_method="Unmeasured; analog pricing (Guidewheel per-sensor SaaS)",
        sam_customers=40_000, sam_arpu=60_000, sam_basis="Pune, Chennai, Rajkot, Coimbatore, Ludhiana, NCR",
        som_customers=(2_000, 4_000), som_arpu=60_000,
        pain="Medium-High", alternatives="Whiteboards, Excel, enterprise MES/IIoT", why_insufficient="Enterprise tools too costly/complex",
        solution="Job cards on WhatsApp, supervisor app, current-sensor clip-ons, OEE and delivery-risk alerts",
        model="Hardware + SaaS", pricing="Rs 10-20k/machine hardware + Rs 1-1.5k/machine/month", competition="Low-Medium",
        acquisition="Cluster demo days, OEM supplier-development programmes, machine-tool dealers",
        mvp_complexity="Medium-High", time_to_mvp="4-6 months", capital="Rs 3-6 cr", gross_margin="50-65%",
        regulatory_risk="Low", tech_risk="Medium", expansion="Quality (O11), energy (O5), procurement", international="Yes",
        evidence="Low-medium (global analogs; India WTP unproven)", category="B",
        matrix=dict(market="Medium", severity="Medium-High", wtp="Medium", competition="Low-Medium", cac="Medium-High", mvp="Medium-High",
                    scalability="Medium", potential="Medium", confidence="Low"),
    ),
    dict(
        id="O11", name="Supplier-quality and traceability SaaS for auto/engineering tier-2/3",
        problems="P21;P40",
        target="Tier-2/3 component makers supplying OEMs and tier-1s",
        tam_customers=65_000, arpu=90_000, customers_basis="Est. 50-80k component makers (low confidence)",
        topdown_low_cr=300, topdown_high_cr=900, topdown_method="Unmeasured", sam_customers=20_000, sam_arpu=90_000,
        sam_basis="Auto clusters", som_customers=(800, 1_500), som_arpu=90_000,
        pain="Medium-High", alternatives="Paper PPAP, Excel, consultants", why_insufficient="No MSME-grade tool",
        solution="PPAP/APQP docs, inspection apps, traceability", model="SaaS", pricing="Rs 5-10k/month",
        competition="Medium", acquisition="OEM/tier-1 supplier programmes", mvp_complexity="Medium", time_to_mvp="4-6 months",
        capital="Rs 2-4 cr", gross_margin="65-75%", regulatory_risk="Low", tech_risk="Low", expansion="Merge into O10",
        international="Medium", evidence="Low", category="C",
        matrix=dict(market="Low-Medium", severity="Medium", wtp="Medium", competition="Medium", cac="Medium", mvp="Medium",
                    scalability="Medium", potential="Low-Medium", confidence="Low"),
    ),
    dict(
        id="O12", name="Labour-code payroll & compliance managed service (10-200 employees)",
        problems="P07;P08;P25",
        target="Manufacturers and service firms with 10-200 workers",
        tam_customers=800_000, arpu=48_000, customers_basis="Est. 6-10 lakh establishments with 10+ workers (low confidence)",
        topdown_low_cr=2_000, topdown_high_cr=4_000, topdown_method="Payroll SaaS + consultant fee pool (unmeasured)",
        sam_customers=200_000, sam_arpu=48_000, sam_basis="Top-50 districts", som_customers=(5_000, 8_000), som_arpu=48_000,
        pain="Medium", alternatives="Consultants, greytHR/Keka/Zoho Payroll, Excel", why_insufficient="Software without done-for-you filings and inspections support",
        solution="Payroll + PF/ESI/labour-code filings + registers + inspection kit, with human compliance desk",
        model="Per-employee managed service", pricing="Rs 100-200 per employee-month", competition="High",
        acquisition="CA firms, industrial estates, associations", mvp_complexity="Medium", time_to_mvp="3 months",
        capital="Rs 2-4 cr", gross_margin="45-60%", regulatory_risk="Low", tech_risk="Low", expansion="Hiring (O16), insurance (O13)",
        international="Low", evidence="Medium", category="B",
        matrix=dict(market="Medium-High", severity="Medium", wtp="Medium", competition="High", cac="Medium", mvp="Medium",
                    scalability="Medium", potential="Medium", confidence="Medium"),
    ),
    dict(
        id="O13", name="Embedded MSME insurance distribution (fire, stock, marine, group health)",
        problems="P36", target="GST-registered MSMEs via SaaS/lending partners",
        tam_customers=5_000_000, arpu=15_000 * 0.15, customers_basis="Assume 50 lakh insurable formal MSMEs; Rs 15k premium; 15% commission",
        topdown_low_cr=800, topdown_high_cr=1_500, topdown_method="Commission pool (unmeasured)",
        sam_customers=1_000_000, sam_arpu=2_250, sam_basis="Reachable via partners", som_customers=(30_000, 60_000), som_arpu=2_250,
        pain="Low until loss", alternatives="Agents, bancassurance", why_insufficient="Low awareness; poor product fit",
        solution="Embedded quotes inside billing/lending flows", model="Commission", pricing="Commission 10-20%",
        competition="Medium", acquisition="Embedded partners", mvp_complexity="Medium", time_to_mvp="4-6 months",
        capital="Rs 3-6 cr", gross_margin="Commission-based", regulatory_risk="High (IRDAI licence)", tech_risk="Low",
        expansion="Credit insurance, trade credit", international="Low", evidence="Low", category="C",
        matrix=dict(market="Medium", severity="Low-Medium", wtp="Low", competition="Medium", cac="Medium-High", mvp="Medium",
                    scalability="Medium", potential="Medium", confidence="Low"),
    ),
    dict(
        id="O14", name="AI digital storefront (website + Google profile + catalogue) for micro manufacturers",
        problems="P11;P12;P13", target="Micro and small firms without web presence",
        tam_customers=10_000_000, arpu=6_000, customers_basis="Theoretical: 1 crore formal-ish MSMEs x Rs 6k/yr",
        topdown_low_cr=300, topdown_high_cr=800, topdown_method="Existing agency/web-builder spend (unmeasured)",
        sam_customers=2_000_000, sam_arpu=6_000, sam_basis="GST-registered B2B micro firms",
        som_customers=(20_000, 40_000), som_arpu=6_000,
        pain="Low", alternatives="Freelancers, Wix, GoDaddy, Hostinger, IndiaMART catalogue", why_insufficient="Commoditised",
        solution="Auto-generated site/catalogue from WhatsApp photos", model="SaaS", pricing="Rs 300-1,000/month",
        competition="Very high", acquisition="Hard (diffuse)", mvp_complexity="Low", time_to_mvp="4 weeks", capital="Rs 0.5 cr",
        gross_margin="70%", regulatory_risk="Low", tech_risk="Low", expansion="Fold into O3", international="Low",
        evidence="Weak WTP", category="D",
        matrix=dict(market="Low (real)", severity="Low", wtp="Low", competition="Very high", cac="High", mvp="Low",
                    scalability="High", potential="Low", confidence="Medium"),
    ),
    dict(
        id="O15", name="Credit-readiness + lender marketplace (CMA/DPR automation on AA/GST data)",
        problems="P37;P02;P32", target="MSMEs seeking Rs 10 lakh-5 cr loans; their CAs",
        tam_customers=300_000, arpu=45_000,
        customers_basis="Assume 10 lakh applications/yr x 30% disbursal; commission ~Rs 45k on Rs 40 lakh avg ticket",
        topdown_low_cr=1_000, topdown_high_cr=1_800, topdown_method="0.75-1.5% DSA commission on MSME loan flow (unmeasured share)",
        sam_customers=90_000, sam_arpu=45_000, sam_basis="Via CA partners in top-100 districts",
        som_customers=(5_000, 9_000), som_arpu=45_000,
        pain="High", alternatives="DSAs, bank RMs, fintech lenders, PSB digital model, ULI",
        why_insufficient="Documentation burden; mismatched lender choice; CA time", solution="Auto CMA/projections from Tally/GST/AA; "
        "eligibility across lenders and CGTMSE; application tracking", model="Commission + report fees", pricing="Rs 5-15k per report; 0.75-1.5% commission",
        competition="High", acquisition="CA firms (via O2), associations", mvp_complexity="Medium", time_to_mvp="3-4 months",
        capital="Rs 3-6 cr", gross_margin="60-70%", regulatory_risk="Medium-High (RBI digital-lending/LSP rules)",
        tech_risk="Low", expansion="Embedded finance in O1/O4", international="Medium", evidence="Medium", category="B",
        matrix=dict(market="Medium-High", severity="High", wtp="High", competition="High", cac="Medium", mvp="Medium",
                    scalability="High", potential="Medium", confidence="Medium"),
    ),
    dict(
        id="O16", name="Cluster skilled-worker staffing with ITI pipelines",
        problems="P23;P24", target="Manufacturers in large clusters",
        tam_customers=1_000_000, arpu=8_000, customers_basis="Assume 10 lakh skilled hires/yr x Rs 8k placement fee (low confidence)",
        topdown_low_cr=500, topdown_high_cr=1_000, topdown_method="Unmeasured", sam_customers=200_000, sam_arpu=8_000,
        sam_basis="5 clusters", som_customers=(7_000, 15_000), som_arpu=8_000,
        pain="High", alternatives="Labour contractors, Apna, WorkIndia, ITIs", why_insufficient="Skill verification and retention",
        solution="Skill-tested worker pool + payroll", model="Placement fee / staffing margin", pricing="Rs 5-12k per hire or 8-12% staffing margin",
        competition="High", acquisition="Clusters", mvp_complexity="Medium", time_to_mvp="3 months", capital="Rs 2-4 cr",
        gross_margin="15-30%", regulatory_risk="Medium (contract labour)", tech_risk="Low", expansion="O12", international="Low",
        evidence="Medium (pain) / Low (WTP)", category="C",
        matrix=dict(market="Medium", severity="High", wtp="Low-Medium", competition="High", cac="Medium", mvp="Medium",
                    scalability="Low-Medium", potential="Medium", confidence="Low"),
    ),
    dict(
        id="O17", name="Micro-merchant bookkeeping/ledger app",
        problems="P04;P25", target="Micro retailers and traders", tam_customers=50_000_000, arpu=300,
        customers_basis="Theoretical", topdown_low_cr=100, topdown_high_cr=300, topdown_method="Observed revenues of incumbents (Khatabook ~Rs 103 cr FY24)",
        sam_customers=None, sam_arpu=None, sam_basis="n/a", som_customers=(0, 0), som_arpu=0,
        pain="Low-Medium", alternatives="Khatabook, OkCredit, Vyapar, myBillBook", why_insufficient="It is sufficient (saturated)",
        solution="n/a", model="Freemium", pricing="n/a", competition="Very high", acquisition="Very high CAC per paying user",
        mvp_complexity="Low", time_to_mvp="n/a", capital="n/a", gross_margin="n/a", regulatory_risk="Low", tech_risk="Low",
        expansion="n/a", international="n/a", evidence="Strong evidence of LOW WTP (OkCredit Rs 23 cr revenue)", category="D",
        matrix=dict(market="Low (real)", severity="Low", wtp="Very low", competition="Very high", cac="High", mvp="Low",
                    scalability="High", potential="Low", confidence="High"),
    ),
    dict(
        id="O18", name="Cross-border payments for MSME exporters", problems="P28", target="Exporters",
        tam_customers=None, arpu=None, customers_basis="Rs 12.39 lakh cr MSME exports",
        topdown_low_cr=1_200, topdown_high_cr=2_500, topdown_method="0.3-0.6% fee on share of export receipts",
        sam_customers=None, sam_arpu=None, sam_basis="n/a", som_customers=(0, 0), som_arpu=0,
        pain="Medium", alternatives="Skydo, BriskPe, Xflow, Wise, Payoneer, banks", why_insufficient="Largely solved",
        solution="n/a", model="Fees", pricing="n/a", competition="Very high", acquisition="Expensive", mvp_complexity="High (PA-CB licence)",
        time_to_mvp="n/a", capital="n/a", gross_margin="n/a", regulatory_risk="High", tech_risk="Low", expansion="n/a", international="n/a",
        evidence="Saturated", category="D",
        matrix=dict(market="Medium", severity="Medium", wtp="High", competition="Very high", cac="High", mvp="High",
                    scalability="High", potential="Low (for new entrant)", confidence="High"),
    ),
    dict(
        id="O19", name="Standalone MSME cybersecurity", problems="P35", target="Digitally active MSMEs",
        tam_customers=5_000_000, arpu=3_000, customers_basis="Theoretical", topdown_low_cr=200, topdown_high_cr=600,
        topdown_method="Unmeasured", sam_customers=None, sam_arpu=None, sam_basis="n/a", som_customers=(0, 0), som_arpu=0,
        pain="Medium when hit", alternatives="Antivirus, bank alerts", why_insufficient="Low perceived risk",
        solution="n/a", model="SaaS", pricing="n/a", competition="Medium", acquisition="Hard", mvp_complexity="Medium",
        time_to_mvp="n/a", capital="n/a", gross_margin="n/a", regulatory_risk="Low", tech_risk="Medium", expansion="Bundle",
        international="n/a", evidence="Low WTP", category="D",
        matrix=dict(market="Low (real)", severity="Medium", wtp="Low", competition="Medium", cac="High", mvp="Medium",
                    scalability="Medium", potential="Low", confidence="Low"),
    ),
]

# Unit economics (ranges). Inputs are assumptions; LTV = ARPU x GM / annual churn.
UNIT_ECONOMICS = [
    # id, arpu_rs, gm, cac_low, cac_high, annual_churn, notes
    ("O1", 60_000, 0.75, 25_000, 45_000, 0.30, "Channel-led via CA firms/associations; success fees lift ARPU in year 1"),
    ("O2", 150_000, 0.80, 40_000, 80_000, 0.18, "CA firms are sticky once client data lives in the tool"),
    ("O3", 48_000, 0.62, 20_000, 35_000, 0.40, "SMB SaaS churn; must prove conversion uplift monthly"),
    ("O4", 240_000, 0.30, 15_000, 30_000, 0.25, "ARPU = 4% take on Rs 60 lakh/yr buyer GMV; GM = contribution after logistics and credit cost"),
    ("O5", 750_000, 0.45, 150_000, 300_000, 0.04, "Per 100 kW site; 10-25 yr contracts; capex not in CAC"),
    ("O6", 192_000, 0.68, 50_000, 150_000, 0.12, "Regulatory recurrence keeps churn low"),
    ("O7", 50_000, 0.55, 10_000, 25_000, 0.80, "Mostly one-off claims; repeat only on new investments"),
    ("O8", 36_000, 0.75, 12_000, 25_000, 0.35, ""),
    ("O9", 200_000, 0.45, 60_000, 120_000, 0.35, "Service-heavy"),
    ("O10", 60_000, 0.58, 40_000, 80_000, 0.20, "Hardware sold at near cost"),
    ("O12", 48_000, 0.52, 20_000, 40_000, 0.20, ""),
    ("O15", 45_000, 0.65, 10_000, 20_000, 0.50, "Per disbursal; repeat via renewals/top-ups"),
]
