"""Public, organisation-level channel partners (no personal data).

These are associations, export promotion councils, chambers and public
facilitation bodies that are the cheapest route to the first 100 customers.
Websites are listed only where we are confident of the official domain;
otherwise left blank. Verify every entry before outreach.
"""

# name, type, city, state, sector focus, relevant opportunities, website
PARTNERS = [
    # National MSME bodies and chambers
    ("Federation of Indian Micro and Small & Medium Enterprises (FISME)", "National MSME association", "New Delhi", "Delhi", "All", "O1;O7;O15", "fisme.org.in"),
    ("India SME Forum", "National MSME association", "Mumbai", "Maharashtra", "All", "O3;O7;O15", "indiasmeforum.org"),
    ("Laghu Udyog Bharati", "National MSME association", "New Delhi", "Delhi", "All (strong in North/West)", "O1;O7;O12", ""),
    ("Chamber of Indian Micro Small & Medium Enterprises (CIMSME)", "National MSME association", "Mumbai", "Maharashtra", "All", "O1;O7", ""),
    ("Confederation of Indian Industry (CII) - MSME councils", "Chamber", "New Delhi", "Delhi", "All", "O5;O6;O10", "cii.in"),
    ("FICCI - CMSME", "Chamber", "New Delhi", "Delhi", "All", "O6;O9", "ficci.in"),
    ("ASSOCHAM - MSME council", "Chamber", "New Delhi", "Delhi", "All", "O6;O9", "assocham.org"),
    ("PHD Chamber of Commerce and Industry", "Chamber", "New Delhi", "Delhi", "North India", "O1;O9", ""),
    ("All India Manufacturers' Organisation (AIMO)", "Manufacturers association", "Mumbai", "Maharashtra", "Manufacturing", "O1;O10", ""),
    ("Confederation of All India Traders (CAIT)", "Traders association", "New Delhi", "Delhi", "Trading", "O15;O13", ""),
    ("NASSCOM (SME council)", "Industry association", "Noida", "Uttar Pradesh", "IT/ITES", "O2;O3", "nasscom.in"),
    ("Indian Industries Association (IIA)", "State MSME association", "Lucknow", "Uttar Pradesh", "All", "O1;O7;O12", ""),
    # Government / public facilitation
    ("SIDBI (incl. Udyam Assist, MSME Pulse)", "Development bank", "Lucknow/Mumbai", "Uttar Pradesh", "All", "O1;O5;O15", "sidbi.in"),
    ("NSIC (National Small Industries Corporation)", "Public sector", "New Delhi", "Delhi", "All", "O8;O15", "nsic.co.in"),
    ("MSME Development & Facilitation Offices (MSME-DFOs, 30+)", "Government", "Pan-India", "Pan-India", "All", "O7;O8;O9", "dcmsme.gov.in"),
    ("District Industries Centres (DICs)", "Government", "Pan-India", "Pan-India", "All", "O7;O9", ""),
    ("Bureau of Energy Efficiency (BEE) SME programme", "Government", "New Delhi", "Delhi", "Energy-intensive clusters", "O5;O6", "beeindia.gov.in"),
    ("TReDS platforms (RXIL, M1xchange, Invoicemart, C2treds, DTX)", "Regulated platforms", "Mumbai", "Maharashtra", "B2B sellers", "O1", ""),
    ("Institute of Chartered Accountants of India (ICAI) - regional councils & branches", "Professional body", "New Delhi", "Delhi", "CA firms", "O2;O1;O15", "icai.org"),
    # Export promotion councils
    ("Federation of Indian Export Organisations (FIEO)", "Export apex body", "New Delhi", "Delhi", "All exports", "O6;O9", "fieo.org"),
    ("EEPC India (Engineering Export Promotion Council)", "Export promotion council", "Kolkata", "West Bengal", "Engineering, steel products", "O6;O9", "eepcindia.org"),
    ("Apparel Export Promotion Council (AEPC)", "Export promotion council", "Gurugram", "Haryana", "Apparel", "O9;O12", "aepcindia.com"),
    ("Cotton Textiles Export Promotion Council (TEXPROCIL)", "Export promotion council", "Mumbai", "Maharashtra", "Cotton textiles", "O9;O4", "texprocil.org"),
    ("Synthetic & Rayon Textiles EPC (SRTEPC)", "Export promotion council", "Mumbai", "Maharashtra", "MMF textiles", "O9;O4", ""),
    ("CHEMEXCIL", "Export promotion council", "Mumbai", "Maharashtra", "Chemicals, dyes", "O6;O9", "chemexcil.in"),
    ("PHARMEXCIL", "Export promotion council", "Hyderabad", "Telangana", "Pharma", "O9", "pharmexcil.com"),
    ("Gem & Jewellery EPC (GJEPC)", "Export promotion council", "Mumbai", "Maharashtra", "Gems & jewellery", "O9", "gjepc.org"),
    ("Council for Leather Exports (CLE)", "Export promotion council", "Chennai", "Tamil Nadu", "Leather & footwear", "O9;O6", ""),
    ("Export Promotion Council for Handicrafts (EPCH)", "Export promotion council", "New Delhi", "Delhi", "Handicrafts", "O9", "epch.in"),
    ("Carpet Export Promotion Council (CEPC)", "Export promotion council", "New Delhi", "Delhi", "Carpets", "O9", ""),
    ("PLEXCONCIL", "Export promotion council", "Mumbai", "Maharashtra", "Plastics", "O9;O4", ""),
    ("CAPEXIL", "Export promotion council", "Kolkata", "West Bengal", "Chemicals & allied (minerals, ceramics, etc.)", "O9;O6", ""),
    ("Cashew Export Promotion Council of India (CEPCI)", "Export promotion council", "Kollam", "Kerala", "Cashew", "O9", ""),
    ("Handloom EPC (HEPC)", "Export promotion council", "Chennai", "Tamil Nadu", "Handloom", "O9", ""),
    ("Electronics & Computer Software EPC (ESC)", "Export promotion council", "New Delhi", "Delhi", "Electronics, software", "O9", ""),
    ("Services Export Promotion Council (SEPC)", "Export promotion council", "New Delhi", "Delhi", "Services", "O9", ""),
    ("APEDA", "Statutory export body", "New Delhi", "Delhi", "Agri & processed food", "O9;O6", "apeda.gov.in"),
    ("MPEDA", "Statutory export body", "Kochi", "Kerala", "Marine products", "O9", "mpeda.gov.in"),
    # Sector associations (national)
    ("Automotive Component Manufacturers Association (ACMA)", "Sector association", "New Delhi", "Delhi", "Auto components", "O10;O11;O1", "acma.in"),
    ("IEEMA", "Sector association", "Mumbai", "Maharashtra", "Electrical equipment", "O10;O1", "ieema.org"),
    ("Indian Machine Tool Manufacturers' Association (IMTMA)", "Sector association", "Bengaluru", "Karnataka", "Machine tools", "O10", "imtma.in"),
    ("All India Plastics Manufacturers' Association (AIPMA)", "Sector association", "Mumbai", "Maharashtra", "Plastics", "O4;O5;O10", ""),
    ("Institute of Indian Foundrymen (IIF)", "Sector association", "Kolkata", "West Bengal", "Foundry", "O5;O6;O10", ""),
    ("Association of Indian Forging Industry (AIFI)", "Sector association", "Pune", "Maharashtra", "Forging", "O5;O6;O10", ""),
    ("All India Induction Furnaces Association (AIIFA)", "Sector association", "New Delhi", "Delhi", "Steel melting/re-rolling", "O6;O5", ""),
    ("Material Recycling Association of India (MRAI)", "Sector association", "Mumbai", "Maharashtra", "Metal recycling", "O6", ""),
    ("Clothing Manufacturers Association of India (CMAI)", "Sector association", "Mumbai", "Maharashtra", "Apparel", "O3;O4;O12", ""),
    ("Indian Drug Manufacturers' Association (IDMA)", "Sector association", "Mumbai", "Maharashtra", "Pharma", "O8;O9", ""),
    ("Federation of Pharma Entrepreneurs (FOPE)", "Sector association", "Mumbai", "Maharashtra", "Pharma MSMEs", "O8", ""),
    ("ELCINA Electronic Industries Association of India", "Sector association", "New Delhi", "Delhi", "Electronics", "O10;O1", ""),
    ("All India Food Processors' Association (AIFPA)", "Sector association", "New Delhi", "Delhi", "Food processing", "O7;O9", ""),
    ("All India Rice Exporters Association", "Sector association", "New Delhi", "Delhi", "Rice exports", "O9", ""),
    ("Seafood Exporters Association of India", "Sector association", "Kochi", "Kerala", "Seafood", "O9;O6", ""),
    ("All India Spices Exporters Forum", "Sector association", "Kochi", "Kerala", "Spices", "O9", ""),
    # Cluster / state associations
    ("Tiruppur Exporters' Association (TEA)", "Cluster association", "Tiruppur", "Tamil Nadu", "Knitwear exports", "O1;O4;O5;O6", ""),
    ("Southern India Mills' Association (SIMA)", "Regional association", "Coimbatore", "Tamil Nadu", "Textiles", "O4;O5", ""),
    ("Coimbatore District Small Industries Association (CODISSIA)", "Cluster association", "Coimbatore", "Tamil Nadu", "Engineering", "O1;O3;O10", ""),
    ("Ambattur Industrial Estate Manufacturers' Association (AIEMA)", "Industrial estate association", "Chennai", "Tamil Nadu", "Engineering/auto", "O1;O10;O11", ""),
    ("Tamil Nadu Small and Tiny Industries Association (TANSTIA)", "State MSME association", "Chennai", "Tamil Nadu", "All", "O1;O7", ""),
    ("Karnataka Small Scale Industries Association (KASSIA)", "State MSME association", "Bengaluru", "Karnataka", "All", "O1;O7;O10", ""),
    ("Peenya Industries Association", "Industrial estate association", "Bengaluru", "Karnataka", "Engineering", "O1;O10", ""),
    ("FKCCI", "State chamber", "Bengaluru", "Karnataka", "All", "O1;O9", ""),
    ("Mahratta Chamber of Commerce, Industries & Agriculture (MCCIA)", "Regional chamber", "Pune", "Maharashtra", "All (auto/engineering)", "O1;O6;O10", ""),
    ("Thane Small Scale Industries Association (TSSIA)", "Industrial estate association", "Thane", "Maharashtra", "Mixed manufacturing", "O1;O12", ""),
    ("Marathwada Association of Small Scale Industries & Agriculture (MASSIA)", "Regional MSME association", "Chhatrapati Sambhajinagar", "Maharashtra", "Auto/engineering", "O1;O10", ""),
    ("Nashik Industries & Manufacturers' Association (NIMA)", "Regional association", "Nashik", "Maharashtra", "Engineering", "O1;O10", ""),
    ("Gujarat Chamber of Commerce & Industry (GCCI)", "State chamber", "Ahmedabad", "Gujarat", "All", "O1;O6;O9", ""),
    ("Southern Gujarat Chamber of Commerce & Industry (SGCCI)", "Regional chamber", "Surat", "Gujarat", "Textiles, diamonds", "O1;O4;O5", ""),
    ("Federation of Gujarat Industries (FGI)", "Regional association", "Vadodara", "Gujarat", "Engineering, chemicals", "O1;O6", ""),
    ("Rajkot Engineering Association", "Cluster association", "Rajkot", "Gujarat", "Engineering", "O1;O3;O5;O6;O10", ""),
    ("Morbi Ceramic Association", "Cluster association", "Morbi", "Gujarat", "Ceramics", "O1;O5;O6", ""),
    ("Vapi Industries Association", "Industrial estate association", "Vapi", "Gujarat", "Chemicals", "O6", ""),
    ("Ankleshwar Industries Association", "Industrial estate association", "Ankleshwar", "Gujarat", "Chemicals", "O6", ""),
    ("Gujarat Dyestuff Manufacturers Association (GDMA)", "Sector association", "Ahmedabad", "Gujarat", "Dyes", "O6;O9", ""),
    ("Rajasthan Chamber of Commerce & Industry", "State chamber", "Jaipur", "Rajasthan", "All", "O9;O7", ""),
    ("Jodhpur Handicrafts Exporters Association", "Cluster association", "Jodhpur", "Rajasthan", "Handicrafts/furniture", "O9", ""),
    ("Mewar Chamber of Commerce & Industry", "Regional chamber", "Bhilwara", "Rajasthan", "Textiles", "O4;O5", ""),
    ("Chamber of Industrial & Commercial Undertakings (CICU)", "Regional association", "Ludhiana", "Punjab", "Engineering, hosiery", "O1;O5;O6;O10", ""),
    ("United Cycle & Parts Manufacturers Association (UCPMA)", "Cluster association", "Ludhiana", "Punjab", "Bicycles & parts", "O1;O10", ""),
    ("Sports Goods Manufacturers & Exporters Association", "Cluster association", "Jalandhar", "Punjab", "Sports goods", "O9", ""),
    ("Faridabad Small Industries Association (FSIA)", "Industrial estate association", "Faridabad", "Haryana", "Engineering/auto", "O1;O10;O11", ""),
    ("Panipat Exporters Association", "Cluster association", "Panipat", "Haryana", "Home textiles", "O1;O9", ""),
    ("Moradabad Handicrafts Exporters Association (MHEA)", "Cluster association", "Moradabad", "Uttar Pradesh", "Metal handicrafts", "O9;O6", ""),
    ("Agra Footwear Manufacturers & Exporters Chamber (AFMEC)", "Cluster association", "Agra", "Uttar Pradesh", "Footwear", "O9", ""),
    ("All India Carpet Manufacturers Association (AICMA)", "Cluster association", "Bhadohi", "Uttar Pradesh", "Carpets", "O9", ""),
    ("Federation of Small & Medium Industries (FOSMI)", "State MSME association", "Kolkata", "West Bengal", "All", "O1;O7;O15", ""),
    ("Federation of Telangana Chambers of Commerce & Industry (FTCCI)", "State chamber", "Hyderabad", "Telangana", "All", "O1;O6", ""),
    ("Bulk Drug Manufacturers Association (BDMA)", "Sector association", "Hyderabad", "Telangana", "Bulk drugs", "O6;O8", ""),
    ("Kerala State Small Industries Association (KSSIA)", "State MSME association", "Kochi", "Kerala", "All", "O1;O7", ""),
    ("Association of Industries Madhya Pradesh (AIMP)", "State association", "Indore", "Madhya Pradesh", "All", "O1;O10", ""),
    ("Pithampur Audyogik Sangathan", "Industrial estate association", "Pithampur", "Madhya Pradesh", "Auto/pharma", "O1;O10", ""),
    ("Adityapur Small Industries Association (ASIA)", "Industrial estate association", "Jamshedpur", "Jharkhand", "Auto/steel ancillaries", "O1;O10;O6", ""),
    ("Urla Industries Association", "Industrial estate association", "Raipur", "Chhattisgarh", "Steel", "O5;O6", ""),
    ("Baddi Barotiwala Nalagarh Industries Association (BBNIA)", "Industrial estate association", "Baddi", "Himachal Pradesh", "Pharma", "O1;O8", ""),
    ("Bihar Industries Association (BIA)", "State association", "Patna", "Bihar", "All", "O7;O15", ""),
]
