"""Problem database (42 problems) and the 14-criterion scoring model.

Scores are 0-10. Two criteria are inverted so that HIGHER IS ALWAYS BETTER
for a startup:
  * competitive_white_space = 10 - competitive intensity
  * regulatory_ease         = 10 - regulatory complexity
Weights favour willingness to pay, existing spend and ease of acquisition,
as the research brief asks.

``confidence`` describes the evidence behind the scores, not the problem's
importance: H = measured by official or large-sample data plus observable
spend; M = some measured data, WTP inferred; L = mostly reasoned.
"""

CRITERIA = [
    # key, label, weight (%), anchor description
    ("customers", "Number of customers affected", 6,
     "10: >1 crore MSMEs; 8: 10 lakh-1 crore; 6: 2-10 lakh; 4: 50k-2 lakh; 2: <50k direct buyers"),
    ("severity", "Pain severity", 8, "10: existential/cash crisis; 5: notable cost; 2: annoyance"),
    ("frequency", "Frequency", 6, "10: daily; 8: weekly; 6: monthly; 4: quarterly; 2: annual or one-off"),
    ("financial_impact", "Financial impact per affected firm", 8,
     "10: >5% of revenue; 7: 2-5%; 5: 1-2%; 3: <1%"),
    ("wtp", "Willingness to pay (evidence)", 12,
     "10: demonstrated large-scale payment for this outcome; 7: some paying segments; 4: stated interest only; 2: expects free"),
    ("existing_spend", "Existing spending pool", 10,
     "10: Rs 1,000 cr+ observable revenue to incumbents; 7: Rs 100-1,000 cr; 4: <Rs 100 cr; 2: negligible"),
    ("competitive_white_space", "Competitive white space (inverse of intensity)", 7,
     "10: few or no credible solutions; 5: several but clear gaps; 2: saturated, funded incumbents or free tools"),
    ("acquisition_ease", "Ease of customer acquisition", 10,
     "10: concentrated buyers or channel with pull; 5: feasible via field/partners; 2: diffuse, high CAC"),
    ("tech_feasibility", "Technology feasibility", 5,
     "10: buildable with current tech in <6 months; 5: needs hardware or deep integrations; 2: research-grade"),
    ("scalability", "Scalability", 7, "10: software-only pan-India; 5: needs local ops; 2: heavy services or capex"),
    ("gross_margin", "Gross-margin potential", 6, "10: >75%; 7: 50-75%; 4: 20-50%; 2: <20%"),
    ("regulatory_ease", "Regulatory ease (inverse of complexity)", 3,
     "10: no licence; 6: data/consumer rules; 3: licensed activity (NBFC, insurance, payments)"),
    ("retention", "Retention potential", 7, "10: system of record or embedded workflow; 5: periodic; 2: one-off"),
    ("expansion", "Expansion opportunity", 5, "10: clear cross-sell and international; 5: some; 2: narrow"),
]

KEYS = [c[0] for c in CRITERIA]
assert sum(c[2] for c in CRITERIA) == 100

# Each problem: id, name, category, who, affected (text), frequency (text), severity (text),
# impact evidence, current solution, current spend evidence, digital readiness, competition,
# startup opportunity, sources, confidence, scores (14 ints, order = KEYS)
PROBLEMS = [
    ("P01", "Delayed B2B payments and receivables collection", "Finance",
     "B2B-selling manufacturers, distributors and service firms",
     "~1-1.5 crore B2B sellers; most acute for 8-12 lakh firms of Rs 2-250 cr turnover",
     "Continuous (weekly follow-ups)", "Very high: working-capital starvation",
     "Rs 7.34 lakh cr delayed (Mar-24, GAME 3.0) / ~Rs 8.1 lakh cr (Economic Survey 2025-26); avg payment 73 days vs 45-day law; "
     "82.6% of invoices carry 0-30 day terms (Recordent 2026); only Rs 55,244 cr (~7%) ever filed on Samadhaan",
     "Phone/WhatsApp follow-ups, lawyers, MSEFC, TReDS (Rs 3.47 lakh cr FY26), credit-bureau reporting (Recordent)",
     "TReDS discount charges; legal/collection fees; no consolidated estimate", "Medium (e-invoice data exists for >Rs 5 cr firms)",
     "Low-Medium: TReDS platforms, KredX, Recordent, generic AR tools; no MSME-native AR copilot at scale",
     "AI receivables copilot + legal escalation (ODR/MSEFC) + embedded invoice finance",
     "S19;S20;S21;S22;S23;S24", "H", [8, 9, 8, 8, 6, 6, 7, 6, 8, 8, 7, 7, 7, 8]),
    ("P02", "Access to affordable working-capital credit", "Finance",
     "Micro and small firms, women-owned, traders",
     "Credit gap Rs 30 lakh cr = 24% of demand; only 41% of MSME borrowers have active formal credit",
     "Monthly", "Very high", "Gap highest for medium (29%), women-owned (35%), trading (33%) (SIDBI-Crisil 2025)",
     "Banks, NBFCs, fintech lenders, CGTMSE, MUDRA (Rs 5.94 lakh cr FY26), PSB digital model (Rs 52,300 cr Apr-Dec 25)",
     "Interest and fees on a very large loan book", "Medium (AA/GST/ULI rails exist)",
     "High: banks, NBFCs (FlexiLoans, Lendingkart, Indifi, Oxyzo), DSAs",
     "Credit-readiness + lender marketplace; cash-flow underwriting on AA/GST",
     "S17;S18;S25;S26;S27;S28", "H", [9, 9, 6, 8, 8, 10, 3, 5, 7, 7, 5, 3, 5, 7]),
    ("P03", "No cash-flow visibility or forecasting", "Finance", "Owners of growing MSMEs",
     "Most GST-registered MSMEs (no measured figure)", "Weekly", "Medium",
     "Profitable firms still run out of cash (73-day cycle, S22); no direct measurement", "Excel, CA, gut feel",
     "Negligible standalone spend", "Low-Medium", "Low in India; Agicap-type tools abroad",
     "Cash-flow module inside AR/AP or banking product (not standalone)", "S22;S57", "L",
     [7, 6, 8, 5, 4, 3, 7, 4, 8, 9, 8, 9, 7, 6]),
    ("P04", "Bookkeeping and GST return preparation (owner side)", "Compliance",
     "All GST filers (1.49 cr normal, 13.6 lakh composition)", "~1.6 crore GSTINs", "Monthly/quarterly",
     "Medium", "CA fees typically Rs 1-5k/month (indicative); late fees and ITC loss on errors",
     "CAs/accountants + Tally/Busy/Marg/Vyapar/myBillBook/Zoho Books", "Large: Tally Rs 500-1,000 cr; Clear Rs 272 cr; CA fee pool",
     "Medium", "Very high (saturated, many free tiers)", "Avoid head-on; serve via CA-firm tooling (P05)",
     "S12;S47;S51", "H", [9, 6, 8, 4, 7, 9, 2, 4, 8, 8, 7, 8, 9, 6]),
    ("P05", "CA-firm productivity: client data collection, entry and reconciliation", "Compliance",
     "~99k CA firms, 1.6 lakh practising CAs, plus non-CA tax practitioners (count unavailable)",
     "~1 lakh firms serving most of the 1.49 crore GST filers", "Daily, peaking at due dates", "High in filing season",
     "Staff shortage and manual data entry from WhatsApp photos, PDFs and bank statements; due-date crunch",
     "Articled staff, Excel, Tally, practice-management tools, GST software", "CAs already buy GST/ITR/Tally software (Rs 5-50k/yr typical, indicative)",
     "High (professional users)", "Medium: Clear, Suvit, Tally add-ons, practice-management tools; AI layer immature",
     "AI copilot for CA firms: WhatsApp document intake, auto-posting to Tally, GSTR-2B/IMS reconciliation, notices",
     "S51;S47", "M", [4, 7, 9, 6, 8, 7, 6, 8, 8, 8, 8, 9, 9, 7]),
    ("P06", "GST input-tax-credit mismatches and notices", "Compliance", "GST normal filers buying from many vendors",
     "~1.49 crore normal filers; acute for multi-vendor buyers", "Monthly", "High when ITC is denied",
     "ITC denial is a direct cash loss; growing data-driven notices", "CA + reconciliation tools (Clear, others)",
     "Part of GST software spend", "Medium", "Medium-High", "Reconciliation + vendor-compliance nudges (bundle into P05)",
     "S12;S47", "M", [8, 7, 6, 6, 6, 6, 4, 5, 8, 8, 7, 8, 7, 4]),
    ("P07", "Payroll, PF/ESI and new labour-code compliance", "Compliance", "Firms with ~10-200 employees",
     "Est. 6-10 lakh establishments (low confidence)", "Monthly", "Medium",
     "Four labour codes effective 21-Nov-2025 change wage definitions and registrations; mfg MSME compliance cost Rs 13-17 lakh/yr (all laws)",
     "Consultants, payroll SaaS (greytHR, Keka, Zoho Payroll, RazorpayX), Excel", "Payroll SaaS + consultant fees",
     "Medium", "High", "Managed payroll + labour-code compliance for 10-200 staff firms", "S29;S52", "M",
     [6, 6, 6, 4, 6, 6, 4, 5, 8, 7, 6, 7, 8, 5]),
    ("P08", "Licences, renewals, factory and environment consents", "Compliance", "Manufacturing units",
     "2.67 lakh ASI factories + unregistered manufacturers", "Quarterly/annual deadlines", "High (penalties, closure risk)",
     "998 unique obligations, 1,456 compliances, 70+ approvals, 59 inspectors per single-state mfg MSME; Rs 13-17 lakh/yr (TeamLease 2025)",
     "Consultants, in-house staff, enterprise compliance tools", "Consultant fees; enterprise RegTech",
     "Low-Medium", "Medium (enterprise-focused vendors)", "Compliance calendar + done-for-you filings for mid-size factories",
     "S29", "M", [6, 7, 4, 5, 6, 6, 6, 5, 7, 6, 6, 7, 8, 5]),
    ("P09", "Finding new customers (lead generation)", "Sales", "B2B manufacturers, traders, service providers",
     "Most MSMEs; 70% rely on traditional marketing", "Daily", "High",
     "Revenue growth constrained; high competition is a top-3 challenge (SIDBI-Crisil 2025)",
     "IndiaMART, Justdial, TradeIndia, referrals, distributors, trade fairs, Google Ads",
     "IndiaMART FY26 revenue Rs 1,569 cr from 2.28 lakh payers (~Rs 69k/yr); Justdial Rs 1,214 cr, 6.3 lakh paid campaigns",
     "Medium", "High (entrenched marketplaces)", "Do not build another marketplace; win on conversion (P10)",
     "S17;S44;S45", "H", [9, 8, 9, 7, 9, 9, 3, 6, 8, 9, 7, 9, 6, 8]),
    ("P10", "Converting and following up leads (slow response, no CRM)", "Sales", "MSMEs already buying leads",
     "~4-6 lakh B2B MSMEs paying for leads; ~15 lakh broader", "Daily", "High",
     "Paid leads wasted when response is slow or language mismatched (no measured India figure)",
     "Owner's phone, WhatsApp Business app, Excel, IndiaMART lead manager, WhatsApp BSP tools",
     "WhatsApp BSPs Rs 1.5-3.5k/month (AiSensy 2.1 lakh accounts); LeadSquared (enterprise)",
     "High (WhatsApp-native)", "Medium: tools exist, not done-for-you vernacular agents for B2B",
     "AI sales agent on WhatsApp/voice: instant vernacular response, qualification, quotes, follow-ups",
     "S44;S45;S49", "M", [8, 7, 10, 6, 7, 6, 6, 7, 8, 9, 7, 8, 8, 8]),
    ("P11", "Creating and maintaining a website", "Digital presence", "Micro and small firms without sites",
     "~7.7 crore establishments lack a site; ~20-35 lakh have one", "One-off", "Low",
     "Limited direct revenue impact for most micro firms", "Freelancers, agencies, Wix/GoDaddy/Hostinger",
     "Fragmented, low-ticket (Rs 3-15k one-time typical, indicative)", "High for basic", "Very high, commoditised by AI",
     "Bundle only (as a lead-capture asset in P10)", "S55;S30", "M", [8, 3, 2, 2, 4, 5, 2, 5, 10, 8, 6, 10, 4, 4]),
    ("P12", "Digital marketing and social media content", "Digital presence", "Consumer-facing and some B2B MSMEs",
     "Only ~13% use digital marketing/e-commerce actively", "Weekly", "Low-Medium", "Uncertain ROI",
     "Agencies, freelancers, Meta/Google self-serve", "Ad spend + agency retainers (fragmented)", "Medium",
     "Very high", "Low priority standalone", "S17;S30", "M", [8, 4, 7, 3, 4, 5, 2, 5, 9, 8, 6, 9, 5, 5]),
    ("P13", "Product catalogues and photography for marketplaces", "Digital presence", "Sellers on B2B/B2C marketplaces",
     "Lakhs of marketplace sellers", "Occasional", "Low", "Lower conversion on poor listings",
     "Photographers, marketplace services, AI image tools", "Small", "Medium", "Medium; AI commoditising",
     "Feature within sales agent / storefront", "S44", "L", [7, 3, 3, 2, 4, 3, 4, 5, 9, 8, 7, 10, 3, 4]),
    ("P14", "Raw-material price volatility", "Procurement", "Manufacturers (metals, polymers, yarn, chemicals)",
     "55.7% of 27,000+ surveyed MSMEs cite it as top procurement challenge", "Weekly", "High",
     "Margin erosion when input prices swing and output prices are fixed", "Phone quotes, trader relationships, OfBusiness-type platforms",
     "Bundled in procurement margins", "Medium", "Medium", "Price intelligence + forward buying inside vertical procurement (O4)",
     "S31;S46", "M", [8, 8, 8, 8, 6, 6, 6, 5, 7, 7, 6, 8, 6, 6]),
    ("P15", "Procurement: supplier discovery, reliability and credit at purchase", "Procurement",
     "Manufacturers and contractors", "MSME procurement worth Rs 124.9 lakh cr; 30-40% digital; 75% spend Rs 10 lakh-1 cr/month (ISF sample)",
     "Weekly", "High", "37.6% struggle managing multiple suppliers; 33.4% lack dependable vendors; 35.6% face payment/credit constraints",
     "Local traders, OfBusiness, Udaan, Moglix, Bizongo, Zetwerk, Infra.Market",
     "OfBusiness FY25 revenue Rs 22,241 cr; Infra.Market Rs 18,472 cr; Zetwerk Rs 12,798 cr; Moglix FY24 Rs 4,964 cr",
     "Medium", "Medium-High (well-funded horizontals)", "Vertical, cluster-specific procurement + embedded credit",
     "S31;S46", "H", [8, 7, 8, 7, 8, 10, 4, 5, 7, 5, 3, 6, 7, 7]),
    ("P16", "Logistics cost penalty for small shippers", "Supply chain", "Small manufacturers",
     "Manufacturers < Rs 5 cr turnover", "Weekly", "Medium-High",
     "Logistics = 16.9% of output for firms < Rs 5 cr vs 7.6% for > Rs 250 cr (NCAER-DPIIT 2025)",
     "Local transporters, aggregators (Shiprocket, Delhivery, Porter, BlackBuck)", "Freight spend is large",
     "Medium", "Medium-High", "Cluster freight pooling/aggregation; tied to procurement or export",
     "S40", "H", [8, 6, 8, 8, 7, 9, 4, 5, 7, 6, 3, 7, 6, 6]),
    ("P17", "Inventory management (stock-outs, dead stock)", "Operations", "Traders, distributors, manufacturers",
     "Most stock-holding MSMEs", "Daily", "Medium", "Working capital locked in slow stock (no India-wide measure)",
     "Billing apps with inventory, Tally, Excel", "Within billing/ERP spend", "Medium", "High",
     "Feature, not company", "S47", "M", [8, 5, 9, 5, 5, 6, 3, 5, 9, 9, 8, 10, 8, 5]),
    ("P18", "Demand forecasting", "Operations", "Distributors, FMCG suppliers, manufacturers",
     "Larger stock-holders", "Monthly", "Low-Medium", "Unmeasured", "Experience, Excel", "Negligible", "Low",
     "Low", "Feature inside procurement/inventory", "", "L", [6, 4, 6, 4, 3, 2, 6, 3, 7, 8, 8, 10, 6, 5]),
    ("P19", "Production planning and job tracking in job shops", "Manufacturing", "Job-work engineering and plastics units",
     "Est. 1-2 lakh units with 10+ workers (low confidence)", "Daily", "Medium-High",
     "Missed delivery dates, idle machines, WIP chaos (no India measurement)", "Whiteboards, Excel, WhatsApp groups",
     "Low; few buy MES", "Low-Medium", "Low for MSME-grade products", "WhatsApp-native production tracking (O10)",
     "S16;S57", "L", [5, 6, 10, 6, 5, 4, 7, 5, 7, 7, 7, 10, 9, 7]),
    ("P20", "Machine downtime and low OEE", "Manufacturing", "CNC/injection moulding/press shops",
     "Subset of ~2.67 lakh ASI factories", "Daily", "Medium-High",
     "Global benchmarks: typical discrete OEE ~60% vs 85% world-class (not India-measured)",
     "Operator logs, OEM service", "Low", "Low", "Low (Indian IIoT vendors target large plants)",
     "Low-cost clip-on sensors + WhatsApp alerts (O10)", "S16;S57", "L", [5, 6, 9, 6, 5, 4, 7, 5, 6, 6, 5, 10, 8, 7]),
    ("P21", "Quality rejections and OEM supplier-quality requirements", "Manufacturing", "Tier-2/3 auto and engineering suppliers",
     "Est. 50-80k component makers (low confidence)", "Weekly", "High (rejections, debit notes)",
     "OEM debit notes and lost business (unmeasured)", "Paper PPAP files, Excel, consultants", "Consultants; some QMS software",
     "Low-Medium", "Medium", "Supplier-quality and traceability SaaS (O11) or module in O10", "S16", "L",
     [4, 7, 8, 6, 6, 5, 6, 6, 7, 6, 7, 9, 8, 6]),
    ("P22", "High energy cost and inefficiency", "Manufacturing", "Energy-intensive units (foundry, forging, ceramics, dyeing, plastics)",
     "Est. 1-1.6 lakh energy-intensive units (low confidence)", "Continuous", "High",
     "Energy 15-40% of production cost in intensive clusters; 10-25% efficiency potential (BEE)",
     "Discoms, diesel gensets, rooftop-solar EPCs, energy auditors", "Large energy bills; C&I solar market",
     "Medium", "Medium (C&I solar players focus on larger customers)",
     "Energy-as-a-service: rooftop solar (RESCO) + monitoring + retrofits financed from savings (O5)",
     "S41", "M", [6, 7, 9, 8, 7, 7, 6, 6, 8, 5, 4, 7, 9, 6]),
    ("P23", "Hiring skilled workers", "Workforce", "Manufacturing and services MSMEs",
     "~25% of MSMEs cite lack of skilled manpower (SIDBI 2025)", "Quarterly", "High",
     "Shortages of up to 35% in unskilled roles; costs +5-8% (industry reports)", "Contractors, referrals, Apna, WorkIndia, ITIs",
     "Job-posting and contractor fees", "Medium", "High", "Cluster staffing with ITI pipelines (O16)", "S67;S54", "M",
     [8, 7, 5, 5, 5, 6, 4, 5, 8, 7, 6, 9, 4, 6]),
    ("P24", "Training and upskilling workers", "Workforce", "Manufacturers", "Broad", "Occasional", "Medium",
     "Productivity loss (unmeasured)", "Government-funded schemes, OEM programmes", "Low (expects subsidy)", "Low",
     "Medium", "Weak standalone; buyer- or govt-funded", "S54", "L", [7, 5, 4, 4, 3, 3, 6, 4, 7, 6, 5, 9, 4, 5]),
    ("P25", "Attendance and wage payments for micro payroll", "Workforce", "Micro firms with 2-20 workers",
     "Large (part of 1.06 crore hired-worker establishments)", "Daily", "Low-Medium", "Small", "Registers, PagarBook-type apps",
     "Small", "Medium", "High", "Avoid standalone", "S01", "M", [8, 4, 10, 3, 4, 4, 3, 5, 9, 9, 7, 9, 7, 4]),
    ("P26", "Finding international buyers (export discovery)", "Exports", "Exporters and export-capable non-exporters",
     "1.73 lakh exporting MSMEs (FY25) + est. 1-2 lakh export-capable non-exporters", "Monthly", "Medium-High",
     "MSME exports Rs 12.39 lakh cr (FY25); 45.8% share of exports", "Trade fairs (EPC-subsidised), Alibaba.com, agents, Volza-type data",
     "Fair costs, marketplace memberships, agent commissions", "Medium", "Medium",
     "Managed export launchpad + buyer data + finance (O9)", "S36;S37", "M", [5, 6, 6, 7, 6, 6, 5, 5, 7, 7, 6, 8, 5, 9]),
    ("P27", "Export documentation and compliance", "Exports", "Exporters", "1.73 lakh exporting MSMEs", "Per shipment",
     "Medium", "Delays, demurrage, missed incentives", "CHAs, freight forwarders, in-house staff", "Service fees",
     "Medium", "Medium-High", "Bundle in O9", "S36", "M", [5, 5, 7, 4, 6, 6, 4, 5, 7, 7, 6, 7, 7, 6]),
    ("P28", "Cross-border payment cost and forex conversion", "Exports", "Exporters, freelancers", "1.73 lakh MSME exporters + freelancers",
     "Per invoice", "Medium", "Bank FX markups and fees", "Banks, Skydo (40k+ exporters), BriskPe, Xflow, Wise, Payoneer",
     "Large FX/fee pool", "High", "Very high (saturated)", "Avoid", "S50", "H", [5, 5, 8, 5, 8, 7, 2, 6, 6, 9, 6, 3, 7, 6]),
    ("P29", "Trade finance for exporters", "Exports", "Small exporters", "1.73 lakh exporters", "Per order", "High",
     "Pre/post-shipment finance gaps; EPM interest subvention 2.75%", "Banks, Drip Capital, ECGC, EPM schemes",
     "Interest and factoring fees", "Medium", "Medium", "Partner, not build (lending licence)", "S37;S50", "M",
     [5, 7, 6, 7, 8, 7, 4, 5, 6, 7, 5, 3, 6, 7]),
    ("P30", "EU CBAM and product carbon-footprint compliance", "ESG/Exports",
     "Steel and aluminium exporters and their suppliers; later more sectors",
     "3-4k direct + 25-30k indirect MSME exporters exposed (CleanCarbon est.)", "Per shipment and annual declarations",
     "Very high: lost orders", "Default values 30-80% above actual emissions; 15-22% price cuts needed (GTRI); orders cancelled",
     "Consultants, global CBAM tools, buyers' templates", "Emerging consulting and verification fees",
     "Low", "Low-Medium (early)", "CBAM/PCF data platform + managed verification for MSME exporters (O6)",
     "S38", "M", [3, 9, 6, 9, 7, 4, 7, 7, 8, 7, 7, 7, 8, 9]),
    ("P31", "ESG/BRSR value-chain data requests from large buyers", "ESG", "Suppliers to top listed companies",
     "Est. 20-50k MSME suppliers in scope (low confidence)", "Annual", "Medium",
     "Risk of delisting as supplier; voluntary FY26, assurance from FY27", "Buyer-provided questionnaires, consultants",
     "Often buyer-paid", "Low", "Medium (ESG SaaS targets the listed buyer)", "Supplier ESG data module sold via buyers (O6)",
     "S39", "L", [4, 5, 4, 4, 5, 4, 5, 7, 8, 8, 7, 8, 7, 8]),
    ("P32", "Discovering and applying for government schemes", "Schemes", "All MSMEs",
     "97.3% unaware of digitalisation schemes (ISF); broad unawareness", "Annual/one-off", "Medium",
     "Unclaimed subsidies and guarantees (unmeasured)", "Consultants, bank staff, Haqdarshak, govt portals",
     "Fragmented success fees", "Low-Medium", "Medium", "Scheme engine as a lead magnet; monetise via O7/O15", "S30;S61", "L",
     [9, 5, 2, 6, 5, 4, 6, 5, 7, 6, 6, 8, 3, 5]),
    ("P33", "Claiming state and central investment incentives", "Schemes", "Firms investing in new capacity",
     "Unmeasured; PMEGP alone targets ~4 lakh projects over 5 years", "One-off per project", "High (large sums)",
     "Capital subsidy, SGST reimbursement, interest subvention often Rs 5 lakh-5 cr per claim (indicative)",
     "Incentive consultants on success fee", "Success fees (common practice; scale unmeasured)", "Low",
     "Medium (fragmented consultants)", "Incentive-claims-as-a-service (O7)", "S30", "L",
     [4, 6, 2, 8, 8, 5, 5, 5, 6, 5, 7, 8, 4, 4]),
    ("P34", "Winning public procurement (GeM/tenders)", "Sales", "MSE sellers on GeM", "11 lakh+ MSEs registered on GeM",
     "Weekly", "Medium", "MSMEs won 47% of GeM order value in FY26 (Rs 2.36 lakh cr)", "Tender-info portals, consultants",
     "Subscriptions and consultant fees", "Medium", "Medium-High", "AI bid desk (O8)", "S34", "M",
     [6, 5, 7, 6, 6, 5, 4, 6, 8, 8, 7, 9, 6, 4]),
    ("P35", "Cybersecurity and payment fraud", "Risk", "Digitally active MSMEs", "~3.1 crore internet-using establishments",
     "Occasional", "Medium-High when hit", "47% of small businesses lost time/money to an incident (2025)",
     "Antivirus, bank alerts", "Low", "Medium", "Medium", "Bundle with banking/insurance; weak standalone", "S43", "M",
     [8, 6, 3, 4, 3, 3, 5, 3, 7, 8, 6, 9, 6, 6]),
    ("P36", "Insurance protection gap", "Risk", "Most MSMEs", "~17% have any insurance (IRDAI-cited, low confidence)",
     "Annual", "High when a loss occurs", "Uninsured fire/stock/health losses", "Agents, bank cross-sell",
     "Premium pool (MSME share unmeasured)", "Medium", "Medium", "Embedded distribution via SaaS partners (O13)", "S42", "L",
     [9, 6, 2, 5, 4, 6, 5, 5, 7, 8, 6, 3, 6, 6]),
    ("P37", "Loan documentation (CMA data, project reports) and credit readiness", "Finance",
     "MSMEs applying for loans of Rs 10 lakh-5 cr", "Lakhs of applications/yr (PSB digital model: 3.96 lakh in 9 months)",
     "Per application", "Medium-High", "Delays and rejections; CA fees per report (indicative Rs 5-25k)",
     "CAs, DSAs, bank officers", "CA/DSA fees", "Medium", "Medium", "Automated CMA/DPR + lender matching (O15)",
     "S27;S51", "M", [7, 6, 3, 4, 7, 5, 6, 7, 8, 8, 8, 8, 4, 6]),
    ("P38", "Owner dashboards / MIS", "Operations", "Growing MSMEs", "Broad", "Weekly", "Low-Medium", "Unmeasured",
     "Tally reports, Excel", "Low", "Medium", "Medium", "Feature", "", "L", [7, 4, 6, 3, 3, 3, 5, 4, 8, 9, 8, 10, 6, 6]),
    ("P39", "Knowing how to adopt AI", "Digital", "Owners", "24% no AI use; 35% experimenting (D&B 2026)", "Ongoing",
     "Low-Medium", "Unmeasured", "YouTube, vendors, consultants", "Low", "Medium", "Medium",
     "Deliver AI inside workflows (O1-O3), not as advice", "S33", "L", [8, 4, 5, 4, 4, 3, 5, 4, 8, 7, 6, 9, 5, 7]),
    ("P40", "Obtaining quality certifications (ISO, BIS, ZED)", "Compliance", "Manufacturers selling to OEMs/govt/exports",
     "Lakhs of manufacturers (unmeasured)", "One-off with renewals", "Medium", "Needed to qualify as supplier",
     "Certification consultants", "Consultant fees", "Low-Medium", "High (fragmented consultants)", "Low priority",
     "S16", "L", [5, 6, 2, 5, 7, 5, 4, 6, 6, 5, 5, 6, 4, 5]),
    ("P41", "Legal recovery of overdue dues (MSEFC/ODR)", "Finance", "Micro and small suppliers with old dues",
     "2.57 lakh Samadhaan applications to Dec-2025; far more never file", "Per dispute", "High",
     "Rs 55,244 cr filed; 52,744 applications (Rs 8,397 cr) not yet examined; new Act adds ODR and 90-day mediation",
     "Lawyers, MSEFC filings", "Legal fees", "Low", "Low", "Productised MSEFC/ODR filing (module of O1)", "S21;S24", "M",
     [6, 8, 3, 8, 7, 5, 8, 6, 7, 7, 7, 6, 4, 5]),
    ("P42", "Bank and UPI reconciliation", "Finance", "GST filers with many digital receipts", "~1.5 crore GST filers",
     "Daily", "Medium", "Unreconciled receipts cause GST and books errors", "Accountants, Tally bank feeds",
     "Within accounting spend", "Medium", "Medium-High", "Feature of P05", "S12", "M", [8, 5, 10, 3, 5, 5, 4, 5, 8, 9, 8, 9, 8, 5]),
]


def weighted_score(scores):
    return round(sum(s * c[2] for s, c in zip(scores, CRITERIA)) / 100, 2)
