"""Source registry. IDs are cited throughout the CSVs and the report.

``tier``: official (government / regulator / statutory body), company
(audited filings, investor presentations), industry (association or
research-institute survey), secondary (news or aggregator reporting an
official figure - verify against the primary before reuse).

Retrieval note: this study was compiled in October 2026 from a sandbox
whose network policy blocked direct page fetches of government portals
(pib.gov.in, mospi.gov.in, data.gov.in, udyamregistration.gov.in) and
many news sites. Figures were therefore captured from search-engine
result extracts of the pages listed here. Every figure should be
re-verified against the primary URL before external use.
"""

SOURCES = [
    # --- Official: MSME population, surveys, registrations -----------------
    dict(id="S01", tier="official", publisher="MoSPI / PIB",
         title="Annual Survey of Unincorporated Sector Enterprises (ASUSE) Results for 2025",
         period="Jan-Dec 2025 (released Mar 2026)",
         url="https://www.pib.gov.in/PressReleasePage.aspx?PRID=2244457&reg=3&lang=1"),
    dict(id="S01b", tier="official", publisher="MoSPI",
         title="Press Note on ASUSE 2025",
         period="Jan-Dec 2025",
         url="https://www.mospi.gov.in/uploads/latestReleases/latest_release_1774347321466_c16ddf22-bfff-4097-88a7-b3134e464d51_Press_Note_ASUSE_2025_English.pdf"),
    dict(id="S02", tier="official", publisher="MoSPI (NSO)",
         title="First district-level estimates of the unincorporated non-agricultural sector (ASUSE 2025), 757 districts",
         period="Jan-Dec 2025 (released Sep 2026)",
         url="https://www.mospi.gov.in/uploads/latestReleases/latest_release_1789035138998_a5c9e7a1-007e-43d5-97a7-efa59a676e81_Press_Note_District_Report_ASUSE_English.pdf"),
    dict(id="S02b", tier="secondary", publisher="The Tribune / BusinessToday / Business Standard / Factly",
         title="Coverage of ASUSE 2025 district estimates (top districts, GVA per worker, emoluments)",
         period="Sep 2026",
         url="https://www.tribuneindia.com/news/asuse-2025/top-50-districts-account-for-nearly-one-third-of-indias-unincorporated-sector-activity-mospi"),
    dict(id="S03", tier="secondary", publisher="IANS / NewKerala / The Hawk (citing Udyam factsheet)",
         title="Udyam combined factsheet as on 15-Mar-2026 (URP + UAP, micro/small/medium, employment)",
         period="15-Mar-2026",
         url="https://www.thehawk.in/news/science/nearly-9-crore-msmes-registered-on-udyam-platforms-generating-38-crore-jobs"),
    dict(id="S04", tier="official", publisher="Ministry of MSME / PIB",
         title="Over 7.83 crore enterprises registered on Udyam Registration Portal (URP); growth trend; state-wise Annexure-I",
         period="as on 28-Feb-2026",
         url="https://www.pib.gov.in/PressReleasePage.aspx?PRID=2246892&reg=3&lang=1"),
    dict(id="S05", tier="secondary", publisher="KNN India (MoS reply, Rajya Sabha)",
         title="Over 8.84 crore MSMEs registered on Udyam platforms",
         period="as on 30-Jun-2026",
         url="https://knnindia.co.in/news/newsdetails/msme/over-884-crore-msmes-registered-on-udyam-platforms-mos-karandlaje"),
    dict(id="S06", tier="secondary", publisher="Legal Suvidha / ANI (Parliament reply)",
         title="9.16 crore MSMEs registered on Udyam Registration Portal and Udyam Assist Platform",
         period="as on 31-Jul-2026",
         url="https://legalsuvidha.com/latest-updates/msmes-registered-on-udyam-210726"),
    dict(id="S07", tier="secondary", publisher="ANI (Lok Sabha written reply, MoS MSME)",
         title="MSMEs report over 8 crore jobs under UDYAM in FY2025-26; Uttar Pradesh leads; activity shares as on 27-Feb-2026",
         period="FY2025-26",
         url="https://aninews.in/news/business/government-says-msmes-now-report-over-8-crore-jobs-under-udyam-uttar-pradesh-leads-states20260723151624/"),
    dict(id="S08", tier="secondary", publisher="IANS / ANI",
         title="Nearly 9 crore MSMEs registered on Udyam platforms, generating 38 crore jobs",
         period="Jul 2026",
         url="https://ianslive.in/nearly-9-crore-msmes-registered-on-udyam-platforms-generating-38-crore-jobs--20260714145911"),
    dict(id="S09", tier="secondary", publisher="DataRankIndia (compilation of Udyam portal data)",
         title="India MSME Statistics 2026: state-wise and district-wise Udyam (URP) registration data",
         period="2026 (as published by compiler)",
         url="https://datarankindia.com/india-msme-statistics/"),
    dict(id="S10", tier="official", publisher="Office of DC (MSME)",
         title="Udyam Registration Bulletin VII - Analysis of Udyam Registration Data",
         period="Sep 2021 data",
         url="https://dcmsme.gov.in/Buletin-VII-Analysis-of-Udyam-Registration-Data.pdf"),
    dict(id="S11", tier="official", publisher="NSO (NSS 73rd round) via Ministry of MSME Annual Report",
         title="Unincorporated non-agricultural MSMEs, 2015-16 (633.88 lakh enterprises, 11.10 crore employment)",
         period="Jul 2015-Jun 2016",
         url="https://msme.gov.in/sites/default/files/FINALMSMEANNUALREPORT2023-24ENGLISH.pdf"),
    dict(id="S12", tier="official", publisher="GSTN (via A2Z Taxcorp summary)",
         title="Nine Years of GST statistical report - 1.67 crore active taxpayers as of 30-Jun-2026",
         period="30-Jun-2026",
         url="https://a2ztaxcorp.net/nine-years-of-gst-taxpayer-base-crosses-1-67-crore-as-indias-digital-indirect-tax-ecosystem-scales-new-milestones-report-highlights-expansion-of-taxpayer-base-192-27-crore-returns-filed-an/"),
    dict(id="S13", tier="official", publisher="GSTN",
         title="A Statistical Report on Completion of 8 Years of GST (turnover-slab distribution)",
         period="FY2024-25 / 30-Jun-2025",
         url="https://tutorial.gst.gov.in/offlineutilities/gst_statistics/8YearsReport.pdf"),
    dict(id="S14", tier="secondary", publisher="GST e-invoice statistics (via InstaFinancials / GST portal)",
         title="e-invoice: 13.1 lakh GSTINs enabled (Oct 2025); 8.56 lakh GSTINs generated e-invoices (Jun 2026)",
         period="Oct 2025 / Jun 2026",
         url="https://blog.instafinancials.com/2025/10/23/e-invoicing-updates-october-2025/"),
    dict(id="S15", tier="secondary", publisher="Probe42 monthly newsletter (MCA data)",
         title="25,52,715 active companies and LLPs out of 36,16,812 ever registered",
         period="Feb 2026",
         url="https://resources.probe42.in/wp-content/uploads/2026/03/Probe-Monthly-Newsletter-February-2026.pdf"),
    dict(id="S16", tier="official", publisher="MoSPI",
         title="Annual Survey of Industries 2024-25 press note (2.67 lakh factories; 2.60 lakh in 2023-24; Tamil Nadu top)",
         period="FY2024-25",
         url="https://www.mospi.gov.in/uploads/latestReleases/latest_release_1790768522303_b1ee6ba9-c9d3-481a-b30e-45a24c7f3729_PIB_Note_ASI_2024-25_English.pdf"),
    dict(id="S64", tier="secondary", publisher="PIB (ASUSE 2023-24) via search extract",
         title="ASUSE 2023-24 state estimates of establishments (UP, WB, MH)",
         period="Oct 2023-Sep 2024",
         url="https://www.pib.gov.in/PressReleseDetailm.aspx?PRID=2097316&reg=48&lang=2"),

    # --- Finance & payments ------------------------------------------------------
    dict(id="S17", tier="industry", publisher="SIDBI with Crisil Intelligence",
         title="Understanding Indian MSME Sector: Progress and Challenges (survey of 2,097 MSMEs, 19 sectors)",
         period="May 2025",
         url="https://www.sidbi.in/uploads/Understanding_Indian_MSME_sector_Progress_and_Challenges_13_05_25_Final.pdf"),
    dict(id="S18", tier="industry", publisher="TransUnion CIBIL - SIDBI",
         title="MSME Pulse (July 2026)",
         period="Mar 2026 data",
         url="https://www.transunioncibil.com/lp/msme-pulse-jul-2026"),
    dict(id="S19", tier="official", publisher="Ministry of Finance (Economic Survey 2025-26) via KNN / news",
         title="Economic Survey 2025-26: ~Rs 8.1 lakh crore locked in delayed payments to MSMEs",
         period="Jan 2026",
         url="https://knnindia.co.in/news/newsdetails/msme/economic-survey-flags-delayed-payments-lack-of-access-to-formal-credit-as-key-challenges-for-msmes"),
    dict(id="S20", tier="industry", publisher="GAME, FISME, C2FO",
         title="Delayed Payments Report 3.0 - Rs 7.34 lakh crore delayed (Mar 2024), down from Rs 10.7 lakh crore (2022)",
         period="Mar 2024 (released Nov 2025)",
         url="https://fisme.org.in/study/delayed-payments-to-msmes-decline-from-rs-10-lakh-cr-to-rs-7-lakh-cr-but-challenges-persist-game-fisme-report/"),
    dict(id="S21", tier="official", publisher="Ministry of MSME Annual Report 2025-26 (MSME Samadhaan)",
         title="2,56,892 delayed-payment applications involving Rs 55,244.31 crore filed up to 31-Dec-2025",
         period="to 31-Dec-2025",
         url="https://smestreet.in/smestreet-exclusive/msme-development-amendment-bill-2026-delayed-payments-analysis-12208060"),
    dict(id="S22", tier="industry", publisher="Recordent",
         title="Indian SME Receivables Report 2026 (~1.1 lakh MSMEs, 10 lakh+ transactions)",
         period="Jun 2026",
         url="https://smestreet.in/infocus/indian-smes-face-mounting-working-capital-stress-as-average-overdue-receivables-cross-383-crore-recordent-12111904"),
    dict(id="S23", tier="official", publisher="RBI entity-wise TReDS statistics; platform disclosures",
         title="TReDS: Rs 3.47 lakh crore discounted in FY2025-26; MSME sellers registered by platform",
         period="FY2025-26 / Jul 2026",
         url="https://www.rbi.org.in/Scripts/TREDSStatisticsView.aspx?TREDSid=52"),
    dict(id="S24", tier="secondary", publisher="LiveLaw / SCC Online",
         title="MSME Development (Amendment) Act 2026: mandatory TReDS for CPSEs, 90-day mediation, ODR, 50% deposit rule",
         period="Aug 2026",
         url="https://www.scconline.com/blog/post/2026/08/04/msme-development-amendment-bill-2026/"),
    dict(id="S25", tier="official", publisher="CGTMSE",
         title="Cumulative guarantees 1.15 crore worth Rs 9.34 lakh crore; ceiling raised to Rs 10 crore (Apr 2025)",
         period="2025-26",
         url="https://www.cgtmse.in/"),
    dict(id="S26", tier="secondary", publisher="IBEF (citing MUDRA)",
         title="PMMY FY26: Rs 5.94 lakh crore sanctioned across 4.93 crore loan accounts",
         period="FY2025-26",
         url="https://www.ibef.org/government-schemes/pradhan-mantri-mudra-loan-bank-yojana"),
    dict(id="S27", tier="official", publisher="Ministry of Finance / PIB",
         title="3.96 lakh MSME loan applications, Rs 52,300 crore sanctioned under PSB digital Credit Assessment Model (Apr-Dec 2025)",
         period="Apr-Dec 2025",
         url="https://www.pib.gov.in/PressReleasePage.aspx?PRID=2216047&reg=6&lang=1"),
    dict(id="S28", tier="secondary", publisher="MediaNama; Sahamati",
         title="Unified Lending Interface live with 64 lenders / 136 data services; Account Aggregator network statistics",
         period="Jan-Jun 2026",
         url="https://www.medianama.com/2026/01/223-unified-lending-interface-64-lenders-136-data-services/"),
    dict(id="S53", tier="secondary", publisher="Taxguru / Business Standard / Busy",
         title="Section 43B(h) 45-day rule (Section 37(2)(g) of Income-tax Act 2025 from 1-Apr-2026) and unintended effects",
         period="2024-2026",
         url="https://taxguru.in/income-tax/finance-ministry-clarifies-section-43bh-45-day-msme-payment-rule.html"),

    # --- Compliance & regulation -------------------------------------------------
    dict(id="S29", tier="industry", publisher="TeamLease RegTech",
         title="Decoding Compliance for Manufacturing MSMEs in India (1,450+ obligations, Rs 13-17 lakh/yr)",
         period="Jun 2025",
         url="https://www.businessworld.in/article/manufacturing-msmes-bear-rs-13-lakh-annual-compliance-burden-report-561596"),
    dict(id="S52", tier="official", publisher="PIB / KPMG / Drishti",
         title="Four Labour Codes effective 21-Nov-2025; Income-tax Act 2025 in force from 1-Apr-2026",
         period="Nov 2025 / Apr 2026",
         url="https://static.pib.gov.in/WriteReadData/specificdocs/documents/2025/nov/doc20251129711301.pdf"),
    dict(id="S51", tier="official", publisher="ICAI",
         title="ICAI Student & Member Report 2025: 4,07,629 members; 1,59,557 with COP; 98,967 firms",
         period="Mar 2025",
         url="https://finance.careers360.com/articles/icai-student-and-member-report-2025"),

    # --- Digital adoption ----------------------------------------------------------
    dict(id="S30", tier="industry", publisher="India SME Forum (Digishaastra, with Meta)",
         title="META Report Card 2025: The State of Digitalisation in Indian MSMEs (7,835 MSMEs)",
         period="2024-25",
         url="https://indiasmeforum.org/digishaastra/assets/docs/Final-META-Report-Card-2025.pdf"),
    dict(id="S31", tier="industry", publisher="India SME Forum",
         title="Digital Procurement Report (27,000+ Udyam MSMEs; Rs 124.9 lakh crore MSME procurement)",
         period="Aug 2026",
         url="https://www.business-standard.com/amp/economy/news/india-s-124-9-trn-msme-procurement-mkt-offers-digital-growth-opportunity-126080601637_1.html"),
    dict(id="S32", tier="industry", publisher="ICRIER",
         title="Annual Survey of MSMEs in India 2025: Role of Digitalisation (2,365 Udyam manufacturing MSMEs)",
         period="2025",
         url="https://icrier.org/pdf/Annual-Survey-MSMEs_India_2025.pdf"),
    dict(id="S33", tier="industry", publisher="Vi Business; Dun & Bradstreet; PwC",
         title="MSME AI adoption studies 2026 (1 in 4 integrated AI; 24% none / 35% experimenting / 37% automating / 5% core)",
         period="2026",
         url="https://www.dnb.co.in/files/reports/BEOT-2026-Publication.pdf"),
    dict(id="S55", tier="industry", publisher="Verisign DNIB; Tucows/NIXI",
         title=".IN registry ~4.1-4.2 million domains (end-2024 / May 2025 migration)",
         period="2024-2025",
         url="https://www.tucowsregistry.com/nixi-whitepaper"),
    dict(id="S56", tier="secondary", publisher="Industry blogs (low confidence)",
         title="WhatsApp India user base (~536 million) and WhatsApp Business usage",
         period="2025-2026",
         url="https://hyperleap.ai/blog/whatsapp-statistics-india-2026"),

    # --- Markets, procurement, exports -------------------------------------------------
    dict(id="S34", tier="official", publisher="Ministry of Commerce / PIB",
         title="GeM: Rs 18.4 lakh crore cumulative GMV; FY26 Rs 5 lakh crore; MSMEs 47% of order value; 11 lakh+ MSEs",
         period="FY2025-26",
         url="https://www.pib.gov.in/PressReleasePage.aspx?PRID=2249335&reg=3&lang=1"),
    dict(id="S35", tier="secondary", publisher="Government statement via IANS; industry",
         title="ONDC: 1.16 lakh retail sellers live (Dec 2025); 3 lakh+ sellers overall (2026)",
         period="Dec 2025 / 2026",
         url="https://ianslive.in/over-116-lakh-retail-sellers-now-live-on-ondc-govt--20251216164816"),
    dict(id="S36", tier="official", publisher="Ministry of MSME (Parliament replies) via news",
         title="Exporting MSMEs 52,849 (FY21) to 1,73,350 (FY25); MSME exports Rs 3.95 to 12.39 lakh crore; share 45.73% (FY24), 45.79% (FY25 to May)",
         period="FY2020-21 to FY2024-25",
         url="https://indiaseatradenews.com/exporting-msmes-up-from-52849-in-2020-21-to-173350-in-2024-25-centre/"),
    dict(id="S37", tier="official", publisher="Cabinet / PIB",
         title="Export Promotion Mission, Rs 25,060 crore (FY26-FY31): Niryat Protsahan and Niryat Disha",
         period="Nov 2025",
         url="https://www.pib.gov.in/PressReleseDetailm.aspx?PRID=2189381&reg=3&lang=2"),
    dict(id="S38", tier="secondary", publisher="KNN India; GTRI; CleanCarbon",
         title="EU CBAM definitive phase from 1-Jan-2026: MSME steel exporters hit; 25-30k indirect and 3-4k direct MSME exporters exposed",
         period="2026",
         url="https://knnindia.co.in/news/newsdetails/msme/indian-steel-msme-exporters-hit-as-eus-cbam-payment-phase-begins"),
    dict(id="S39", tier="official", publisher="SEBI (via practitioner summaries)",
         title="BRSR Core value-chain disclosures: voluntary for top 250 listed cos from FY2025-26, assessment/assurance from FY2026-27",
         period="Mar 2025 circular",
         url="https://earth5r.org/brsr-value-chain-disclosure-supplier-esg-data-gap/"),
    dict(id="S40", tier="official", publisher="NCAER for DPIIT",
         title="Assessment of Logistics Cost in India: 7.97% of GDP (FY24); firms <Rs 5 cr turnover pay 16.9% of output vs 7.6% for >Rs 250 cr",
         period="FY2023-24 (Sep 2025)",
         url="https://ncaer.org/wp-content/uploads/2025/09/NCAER_Logistic_Study_Report_Sept2025.pdf"),
    dict(id="S41", tier="official", publisher="BEE / SAMEEEKSHA / literature",
         title="MSMEs ~25% of industrial energy use; 10-25% efficiency potential; energy 15-40% of production cost in intensive clusters",
         period="various",
         url="https://beeindia.gov.in/content/energy-efficiency-smes"),
    dict(id="S70", tier="secondary", publisher="FIEO / Business Standard",
         title="State-wise merchandise exports FY2024-25 (Gujarat $116.3 bn, Maharashtra $65.9 bn, TN $52.1 bn, Karnataka $30.5 bn, UP $22 bn)",
         period="FY2024-25",
         url="https://www.business-standard.com/economy/news/gujarat-remains-top-exporting-state-in-fy25-with-9-83-trn-exports-fieo-125080501577_1.html"),

    # --- Risk, insurance, skills -------------------------------------------------------
    dict(id="S42", tier="secondary", publisher="Tata AIA / Riskcovry (citing IRDAI study) - low confidence",
         title="~17% of MSMEs have any insurance; 31% health-insurance penetration in MSMEs vs 85% in large corporates",
         period="undated",
         url="https://www.riskcovry.com/pulse-under-penetration-of-insurance-in-msme-sector/"),
    dict(id="S43", tier="secondary", publisher="BW Businessworld",
         title="Nearly 47% of Indian small businesses lost time or money to a cyber incident in the past 12 months (APAC avg 37%)",
         period="2025",
         url="https://www.businessworld.in/article/survey-reveals-nearly-half-of-indian-smes-faced-cyber-incidents-in-2025-608641"),
    dict(id="S54", tier="official", publisher="NITI Aayog with Institute for Competitiveness",
         title="Enhancing Competitiveness of MSMEs in India",
         period="May 2025",
         url="https://www.pib.gov.in/PressReleasePage.aspx?PRID=2126063&reg=48&lang=2"),

    # --- Companies / competitors ------------------------------------------------------------
    dict(id="S44", tier="company", publisher="IndiaMART InterMESH",
         title="Q4 & FY26 results: revenue Rs 1,569 crore; collections Rs 1,857 crore; 2,28,000 paying suppliers",
         period="FY2025-26",
         url="https://investor.indiamart.com/files/IndiaMART_Q4FY26_Press_Release-v3.pdf"),
    dict(id="S45", tier="company", publisher="Just Dial",
         title="FY26 results: operating revenue Rs 1,213.9 crore; paid campaigns 6,31,530; active listings 54.7 million",
         period="FY2025-26",
         url="https://www.investywise.com/just-dial-q4-fy26-financial-results"),
    dict(id="S46", tier="secondary", publisher="Entrackr / BW Disrupt / ipocentral",
         title="OfBusiness FY25 revenue Rs 22,241 cr; Oxyzo FY25 revenue Rs 1,207 cr; Zetwerk FY25 Rs 12,798 cr; Infra.Market FY25 Rs 18,472 cr; Moglix FY24 Rs 4,964 cr",
         period="FY2024-25",
         url="https://entrackr.com/fintrackr/inframarket-reports-over-2-bn-gross-revenue-in-fy25-profit-falls-42-10991551"),
    dict(id="S47", tier="secondary", publisher="Tracxn / Entrackr / Inc42 / Business Standard",
         title="Tally FY25 revenue Rs 500-1,000 cr (range); Zoho FY25 Rs 12,313 cr; Clear FY25 Rs 272 cr; Razorpay FY25 Rs 3,783 cr; OkCredit FY25 Rs 23.3 cr; Khatabook FY24 Rs 102.7 cr; IndiaFilings FY25 Rs 88.5 cr",
         period="FY2023-24 to FY2024-25",
         url="https://entrackr.com/fintrackr/clear-reports-rs-272-crore-revenue-and-rs-96-crore-loss-in-fy25-10808038"),
    dict(id="S48", tier="secondary", publisher="Accion / company releases",
         title="FlexiLoans AUM > Rs 3,000 cr, 70,000+ MSMEs; Lendingkart cumulative Rs 18,700 cr disbursed",
         period="2025-2026",
         url="https://www.accion.org/news/flexiloans-secures-a-further-45mn-to-empower-indian-msmes/"),
    dict(id="S49", tier="secondary", publisher="Vendor sites / comparison blogs",
         title="WhatsApp BSP pricing (Wati ~Rs 2,499/mo; AiSensy Rs 1,500-3,500/mo; Interakt Rs 2,499-3,499/mo; Gallabox ~Rs 2,399/mo); AiSensy 2,10,000+ businesses",
         period="2026",
         url="https://m.aisensy.com/blog/whatsapp-api-providers/"),
    dict(id="S50", tier="secondary", publisher="Skydo / Entrepreneur India / IBS Intelligence",
         title="Skydo 40,000+ exporters (May 2026), ~$19.7m raised; Drip Capital Rs 10,000 cr MoU with Maharashtra; BriskPe $5m seed",
         period="2025-2026",
         url="https://fintechobserver.substack.com/p/skydo-indias-cross-border-payments"),
    dict(id="S57", tier="secondary", publisher="TechCrunch / Bloomberg / Business Wire / Crowdfund Insider (global analogs)",
         title="Pennylane (EUR 115m ARR 2025), Agicap ($100m 2021), Katana (EUR 14m Series B ext., 1,500 SMBs), Guidewheel ($9m Series A), MachineMetrics ($20m Series B), Moniepoint ($200m+ Series C; $700m MSME loans 2025), Konfio ($227m credit line), BukuWarung ($80m; 6.5m users), Mekari ($50m), KiotViet ($45m; 150k MSMEs), C2FO (~2 lakh suppliers in India network)",
         period="2021-2026",
         url="https://www.businesswire.com/news/home/20251002273715/en/Katana-Extends-Series-B-with-Cogito-Capital-as-Lead-Joined-by-Benchmarks-Peter-Fenton"),
    dict(id="S58", tier="official", publisher="Technical Group on Population Projections (via StatisticsTimes)",
         title="Projected state population, 2026",
         period="1-Jul-2026",
         url="https://statisticstimes.com/demographics/india/indian-states-population.php"),
    dict(id="S59", tier="official", publisher="Ministry of MSME / DPIIT / FMC",
         title="MSE-CDP (606 projects approved, 364 completed); ODOP (1,102 products, 761 districts); FMC cluster mapping (~6,600 clusters)",
         period="2010-2026",
         url="https://www.pib.gov.in/PressReleasePage.aspx?PRID=2240160&reg=3&lang=1"),
    dict(id="S60", tier="secondary", publisher="NSE / BSE via news",
         title="NSE Emerge 731 companies (May 2026); ~580 companies listed on BSE SME",
         period="2026",
         url="https://www.businesstoday.in/amp/markets/ipo-corner/story/nse-emerge-hits-700-sme-listings-milestone-in-2025-508898-2025-12-31"),
    dict(id="S61", tier="company", publisher="Haqdarshak",
         title="Scheme-access platform covering 6,000+ central and state schemes; bank partnerships for MSME scheme access",
         period="2025-2026",
         url="https://msme.haqdarshak.com/"),
    dict(id="S63", tier="official", publisher="SIDBI",
         title="Udyam Assist Platform (launched 11-Jan-2023) for informal micro enterprises via designated agencies",
         period="2023",
         url="https://www.sidbi.in/udyam-assist-platform"),
    dict(id="S66", tier="secondary", publisher="DataRankIndia",
         title="District-wise Udyam (URP) registrations: Gujarat, Tamil Nadu, Maharashtra",
         period="2026 (as published by compiler)",
         url="https://datarankindia.com/gujarat-msme-statistics/"),
    dict(id="S71", tier="secondary", publisher="Inc42 / TechCrunch / ipoplatform (company coverage)",
         title="Infinite Uptime ($35m Series C); Altizon (270+ IIoT projects, 130+ enterprises); Indian IIoT pricing ranges",
         period="2023-2026",
         url="https://inc42.com/startups/altizon-iiot-platform-manufacturing-42next/"),
    dict(id="S67", tier="industry", publisher="SIDBI (via SMEStreet/YourStory)",
         title="About one-fourth of surveyed MSMEs cite lack of skilled manpower as a major challenge",
         period="2025",
         url="https://smestreet.in/msme-opportunities/msmes-and-the-skill-gap-why-hiring-remains-a-top-challenge-9535630"),
]

SOURCE_INDEX = {s["id"]: s for s in SOURCES}
